### ISSUE TITLE
Unable to install on windows 10 or osX

### ISSUE THREAD

**Issue by akatriel** [material-theme/vsc-material-theme#1226]
### Summary
Unable to install.

### Expected behavior
Should be able to install and activate.

### Actual behavior
Output from console:
Package Control: The dependency 'markupsafe' is not currently installed; installing...
Package Control: The dependency 'markupsafe' has successfully been installed or updated
Package Control: The dependency 'python-jinja2' is not currently installed; installing...
Package Control: The dependency 'python-jinja2' has successfully been installed or updated
Package Control: The dependency 'mdpopups' is not currently installed; installing...
Package Control: The dependency 'mdpopups' is not available
Package Control: The dependency 'mdpopups' could not be installed or updated

### Steps to reproduce
1. install package control
2. ctrl shift p install package
3. material theme

### Environment

* Operating system and version:
  * [ X] Windows 10
  * [ X] Mac OS ...
* Sublime Text:
  * Build 3143
* Material Theme release:
  * Most recent as of this post

**Comment by matthewjmink** [comment]
I have the same issue. The dependency ```mdpopups``` appears to be the hold up.

**Comment by equinusocio** [comment]
I think this dep should be updated @zpreston123 Any idea?
https://github.com/facelessuser/sublime-markdown-popups

**Comment by zpreston123** [comment]
@equinusocio I would restart Sublime Text after installing Package Control, then install the theme.  It should install mdpopups automatically.

**Comment by equinusocio** [comment]
I think the problem is that this dependency have now a different name

**Comment by zpreston123** [comment]
@akatriel @matthewjmink Check this out:  https://github.com/wbond/package_control/issues/1334.  This issue could be caused by a bug in Package Control that didn't install mdpopups, but seems to be resolved.

Try reinstalling the theme and let me know what happens.

**Comment by xxxlee** [comment]
I encountered the same problem.
Open the terminal：
sudo pip install python-jinja2
sudo pip install markupsafe
sudo pip install mdpopups
Finally restart.

**Comment by zpreston123** [comment]
Please refer to this issue:  https://github.com/wbond/package_control/issues/1334.

It's a bug in Package Control.  Hopefully it gets resolved soon.

**Comment by filmico** [comment]
Hi Guys, I was having the same issue regarding mdpopups with sublime3 and win7.
Just checking on google for "sublime text3 install mdpopups" found a link that says...

Remember, MdPopups is for Sublime Text 3 builds 3124+.

This can be the issue with mdpopups as mine was and old build (3114)
I'll come back once I get Sublime upgraded!
