### ISSUE TITLE
when i use butterknife ,the candidate box display character incomplete

### ISSUE THREAD

**Issue by xxxiaokay** [material-theme/vsc-material-theme#1235]
win10,Android Studio3.1
u can see the detial in the screenshot
1.use material theme ui:
![20180402104820](https://user-images.githubusercontent.com/16550319/38181097-8d6e63b8-3663-11e8-8c23-5fafb51863c8.png)
2.use default ui:
![20180402104902](https://user-images.githubusercontent.com/16550319/38181115-ab6a2fd2-3663-11e8-8006-20cfaa58bd05.png)

**Comment by mallowigi** [comment]
This is not the right repository, besides this is not something that can be fixed easily. Either disable the Material Theme or bear with it.
