### ISSUE TITLE
"materialTheme.accent": "Remove accents" does not work

### ISSUE THREAD

**Issue by wdanilo** [material-theme/vsc-material-theme#1260]
**Describe the bug**
Hi, I've chosen the "Remove accents" option from `Material Theme: set accent color` menu and it does not work. Moreover, in the `settings.json` file I see a warning that this value is not accepted:

<img width="941" alt="CleanShot 2023-02-01 at 10 30 56@2x" src="https://user-images.githubusercontent.com/1623053/216004607-c771ca4d-3fd7-4de8-9ba8-7f9790667b3a.png">

**Comment by equinusocio** [comment]
Hello, there is no "Remove accents" option... The error message is pretty clear. That option is to set one of the available accent colors, to restore the default one (Teal), just remove the option.
