### ISSUE TITLE
Allow changing breadcrumbs height and icons.

### ISSUE THREAD

**Issue by wdanilo** [material-theme/vsc-material-theme#1261]
Hi, currently my breadcrumbs look different than file tree view. The height is too small and the arrow icons are different. Would it be possible to add styling for those elements, please? :) 

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1623053/216798048-faacf0f3-6052-4ea6-ad63-deb3a0738dfd.png">

**Comment by equinusocio** [comment]
Hello, atm there is no API to do what you're asking.
