### ISSUE TITLE
Set accent color command can't work

### ISSUE THREAD

**Issue by Kayxue** [material-theme/vsc-material-theme#1262]
**Describe the bug**
When I pressed ctrl + shift + p and chose "Material Theme: Set accent color", it didn't show a color list to let me choose.
Yeah I chose that command, and nothing happened.

**To Reproduce**
1. Pressed ctrl + shift + p
2. Select "Material Theme: Set accent color" to choose a color.
3. It happened.

**Expected behavior**
It will show up a list and let me choose which color I want to change.

**Screenshots**
![Recording 2023-03-08 215649](https://user-images.githubusercontent.com/26020165/223732046-51d2f90a-e7a6-4ab3-8e46-2982e3317cfc.gif)

**Additional context**
VSCode Version: 1.76.0
Material Theme Version: 33.6.0

**Comment by equinusocio** [comment]
Hello, we can't reproduce the issue in any of our machines. The gif is not really clear.
