### ISSUE TITLE
No consistency

### ISSUE THREAD

**Issue by oscar-wos** [material-theme/vsc-material-theme#1264]
Hi, I'm using materials theme dark high contrast and the syntax highlighting does not match for the same file type

![image](https://user-images.githubusercontent.com/29248751/227767268-2be89f1a-d078-47b0-8152-f3e3408394de.png)

![image](https://user-images.githubusercontent.com/29248751/227767007-9528e223-6e42-4043-84ec-2fe47d876b09.png)

![image](https://user-images.githubusercontent.com/29248751/227767140-d4eceb91-085c-4a5f-9d7f-d4b984919527.png)

**Comment by equinusocio** [comment]
Hello, we don't provide support for third-party apps. On vscode, the syntax highlight is working as expected on all variants.
