### ISSUE TITLE
Improve the brightness of the default Material theme

### ISSUE THREAD

**Issue by Jemmy512** [material-theme/vsc-material-theme#1265]
Dear team,

I hope this message finds you well. I'm currently using the default Material theme and I am quite fond of it. However, I have noticed that the theme's brightness is not as clear during the daytime compared to its clarity at night. I am reluctant to switch to other themes and am hoping for a solution that allows me to maintain the default Material theme while improving its brightness.

I have attempted to increase the brightness of my screen, but this has resulted in other applications becoming overly bright. I was wondering if there are any convenient configurations or settings that could be implemented to improve the brightness of the default Material theme.

Thank you very much for your time and assistance.

**Comment by equinusocio** [comment]
Hello, we recommend using a bright theme while outside or in bright environments. Material Theme provides a `Light` variant for this. Darker variants are designed to be used in normal/low light environments and increasing the overall luminosity and contrast will compromise the experience.
