### ISSUE TITLE
Accent colour does not change (VSCodium)

### ISSUE THREAD

**Issue by sentreal** [material-theme/vsc-material-theme#1269]
**Describe the bug**
Theme installs correctly and the different variants apply correctly, but the option to change the accent in the extension settings has no effect on the UI.

**To Reproduce**
1. Go to Settings
2. Click Extensions
3. Scroll down to Material Theme
4. Change Accent

**Expected behavior**
Accent change is reproduced in UI, perhaps with invitation to reload window.

**Screenshots**
<img width="1232" alt="Screenshot 2023-08-16 at 08 19 57" src="https://github.com/material-theme/vsc-material-theme/assets/20587599/9a60ac58-55cf-4145-bdf2-4d222bb85924">

**Additional context**
I am using VSCodium rather than VSCode if this could be an issue.

**Comment by equinusocio** [comment]
Hello, we only support Visual Studio Code.

**Comment by sentreal** [comment]
I have now tried this on Visual Studio Code and can confirm the setting is still broken.
