### ISSUE TITLE
Issue with macro bracket color inconsistency

### ISSUE THREAD

**Issue by nowheredevel** [material-theme/vsc-material-theme#1270]
**Describe the bug**
I've only noticed this issue in Rust, but when using proc macros in Rust there appears to be a coloring issue in all Material themes where the first bracket and last bracket have different colors.

**To Reproduce**
1. Install any Material theme, community or official
2. Create a new rust file or project, doesn't matter as long as you're editing a Rust file
3. Use any proc macro with this form: `#[...]`
4. The first bracket will be a different color than the last bracket, which shouldn't happen in my opinion.

**Expected behavior**
Ideally, when given a pair of brackets, the first and last bracket should be the same color. When using the Material theme and using brackets in other contexts, for example when creating an array, the first and last bracket are indeed the same color. In other themes, this consistency also applies to Rust's proc macros, however the Material theme doesn't keep this consistency.

**Screenshots**
![A proc macro having the described issue](https://github.com/material-theme/vsc-material-theme/assets/113222579/7bc51c8a-a0c2-48d7-96bb-5cf7d2912d7b)
![Another proc macro with the same issue](https://github.com/material-theme/vsc-material-theme/assets/113222579/7365e06f-0e2b-49ca-8c15-7a62d3ed6f3d)

**Additional context**
As mentioned before, almost every other theme I've used does not have this issue, so I hope this can be fixed. I apologize if this has been asked before.

**Comment by equinusocio** [comment]
Hello, we are not able to reproduce the issue with the native vscode rust language. If you're using an extension is probable that the extension is assigning the wrong scope to the brackets. We can't help with this, but you can try to override the color using the [scope inspector](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector) 

![CleanShot 2023-08-26 at 11 49 50](https://github.com/material-theme/vsc-material-theme/assets/10454741/a4c59897-7448-4686-bf1a-6e72d6c7c38c)
