### ISSUE TITLE
Selecting Deep Forest High Contrast theme does nothing

### ISSUE THREAD

**Issue by varunbpatil** [material-theme/vsc-material-theme#1271]
**Describe the bug**
Selecting Deep Forest High Contrast theme does nothing. The previously selected theme remains.

**To Reproduce**
1. Go to 'Preferences: Color Theme'
2. Click on 'Deep Forest High Contrast' theme
3. No change in color theme

**Expected behavior**
Deep Forest High Contrast theme to be applied.

**Comment by shawnrivers** [comment]
Looks like it has been fixed in the latest version.
https://github.com/material-theme/vsc-material-theme/commit/a2cf8dc4480f655dd757a33108990f4c7bc52ca4

**Comment by varunbpatil** [comment]
> Looks like it has been fixed in the latest version. [a2cf8dc](https://github.com/material-theme/vsc-material-theme/commit/a2cf8dc4480f655dd757a33108990f4c7bc52ca4)

Indeed. Thank you!
