### ISSUE TITLE
>Yeah I don't fully understand why the change to deprecate the community theme when the official one hasn't had many updates and seems way less polished

### ISSUE THREAD

**Issue by jamesbellnet** [material-theme/vsc-material-theme#1275]
>Yeah I don't fully understand why the change to deprecate the community theme when the official one hasn't had many updates and seems way less polished

You clearly don't know the tools you're using. The community version was first released in 2016, has never been updated since then, and was deprecated years ago. It was on the marketplace to give ppl time (actually years) to migrate. The official material theme supports new vscode features like semantic highlighting (which you can disable to restore old colors). Keep using obsolete and stolen work 👍

You ppl should learn how to work with open-source projects and read README files, [there is a whole section about how to customize the theme](https://github.com/material-theme/vsc-material-theme?tab=readme-ov-file#override-theme-colors), while supporting the project, instead of releasing cloned extensions.

There are people working for free on this open-source project, you're just disrespectful.

@azzazkhan if you want to support open source, read [how to customize the theme](https://github.com/material-theme/vsc-material-theme?tab=readme-ov-file#override-theme-colors) based on your personal taste and stop using stolen work.

_Originally posted by @equinusocio in https://github.com/material-theme/vsc-material-theme/issues/1273#issuecomment-1833306434_

Sorry I have to address this - there is nothing "stolen" about this work, nor do I mean any disrespect. I think you're failing to understand the meaning of open source and the Apache 2.0 license that you licensed this software under.

Firstly, I altered the README to declare that this is a fork of the now deprecated original theme, and kept the link to the official material theme as it was. I also kept the author as it was under package.json, and any other links to related packages (i.e. the material icon theme).

I, like others, tried installing the official theme and noticed many differences from the community version that I was using. I didn't like those differences, nor do I have time to go through and make lots of changes in my settings.json file. I took it upon myself to keep the "COMMUNITY" material theme going, offloading any burden from yourself and hosting it myself for others that also don't want to customise the official version, but instead just want to stick with the theme they've been using for many years.

I have no intention to modify this theme, steal anyones work or fail to credit the original authors. As you can see from this issue, people liked the community theme as it was, and want to stick with it. All I have done is provided that, and by releasing software as open source and licensing it under the Apache 2.0 license you are granting permission for people to do as such.

**Comment by equinusocio** [comment]
Read again the APACHE 2.0 license.

**Comment by jamesbellnet** [comment]
From the Apache 2.0 license:

```
4. Redistribution. You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:
```

You are still credited as the original author, and I appreciate your work and that of the other contributors. Again, I'm just trying to keep a theme alive that many of us still use. Thank you 🙏🏻
