### ISSUE TITLE
Deprecated Community Material Theme inside Material Theme?

### ISSUE THREAD

**Issue by VladimirMikulic** [material-theme/vsc-material-theme#1280]
**Describe the bug**

Deprecated Community Material Theme inside Material Theme comes installed with Material Theme extension.

![Screenshot_20231130_223940](https://github.com/material-theme/vsc-material-theme/assets/35997844/fba67c6a-d63b-4fad-bfd9-fb751fad1204)

**To Reproduce**

1. Go to extensions tab inside VS Code
2. Find Material Theme extension
3. Click on extension pack tab
4. See Community Material Theme inside pack

**Expected behavior**

I'd expect deprecated Community Material Theme to not be inside Material Theme (and thus installed with it).

**Screenshots**

See above.

**Comment by equinusocio** [comment]
😂 We'll fix it soon

**Comment by equinusocio** [comment]
Release on the way

**Comment by VladimirMikulic** [comment]
Thank you so much!
