### ISSUE TITLE
Parameters inside of functions are red for a quater of a second then white.

### ISSUE THREAD

**Issue by Autumnlight02** [material-theme/vsc-material-theme#1281]
**Describe the bug**
I updated from the deprecated version to the current version. When I change between themes it's red for a brief second as I used to have and then it turns white. Other's don't work at all. How can I have parameters, constructor parameters, and constant variables with the color red again?

Edit: this keyword is also blue, how do I change it x-x
**To Reproduce**
Switch between two random themes. You see first the theme apply, and then a short delay later parameter and variable colors (if its a const in ts) switch.

**Expected behavior**
That my const and local variables are red instead of white (less clarity). 

**Screenshots**

https://github.com/material-theme/vsc-material-theme/assets/68244453/7df97e6b-8daf-4e23-aac8-2a1ab1c6c5d2

**Additional context**

**Comment by equinusocio** [comment]
Have you tried to disable vscode semantic highlight?

**Comment by FabianMontoya** [comment]
I'm having the same Issue, I don't know if it's settings problem or what:

#1283

**Comment by Autumnlight02** [comment]
> Have you tried to disable or enable the vscode semantic highlight feature?
> 
> If the semantic highlight doesn't solve your issue you can try to [customize the colors](https://github.com/material-theme/vsc-material-theme/discussions/1274) or install the [old version](https://github.com/material-theme/vsc-material-theme/discussions/1278).

turning this option off helped a lot! But I am a bit confused on how I get const red again, in the example file there is just a singular variable keyword and they are not differenciated as ive seen.

**Comment by FabianMontoya** [comment]
@equinusocio any solution for this issue??

**Comment by FabianMontoya** [comment]
@Autumnlight02 I found a temporary solution, while it's solve by the theme.
You must to change the `Semantic Highlight Guide` setting to false, and the color is correctly set to red, as it should be.


![Screenshot 2023-12-02 at 10 10 40 PM](https://github.com/material-theme/vsc-material-theme/assets/37662924/d1c36655-2f0f-441f-84cc-7ebc6f53ce70)

---

![Screenshot 2023-12-01 at 12 44 54 PM](https://github.com/material-theme/vsc-material-theme/assets/37662924/215769c5-7ed9-4d48-b189-1f5bf7b2c2fb)

**Comment by equinusocio** [comment]
There will not be any fix since there is no bugs. Semantic highlight is a vscode feature and you can disable it. Also check our discussions to see how to customize every color.
