### ISSUE TITLE
Token color customizations do not work properly

### ISSUE THREAD

**Issue by MathiasKandelborg** [material-theme/vsc-material-theme#1288]
**Describe the bug**
I naively installed Material Theme and uninstalled the community version on my Insiders edition.

All the customizations I spent a little while on fine-tuning, are completely whack.

Luckily, I could run the community version on the normal VS Code branch and sync my settings.

**To Reproduce**
1. Use settings as described below (change the theme name accordingly)
2. Use old deprecated theme extension - look at some code
3. Use new theme extension - look at some code
4. Behold the changes

**Expected behavior**
These settings:
```"editor.tokenColorCustomizations": {
    "[Community Material Theme Darker High Contrast]": {
      "comments": {
        "fontStyle": "italic",
        "foreground": "#696969"
      },
      "strings": {
        "fontStyle": "italic",
        "foreground": "#42af6e"
      },
      "keywords": {
        "foreground": "#69afad"
      },
      "variables": {
        "foreground": "#cacaca",
        "fontStyle": "italic"
      },
      "functions": "#63a2e7",
      "types": "#d16cc5",
      "textMateRules": [
        {
          "scope": "variable.other.constant",
          "settings": {
            "fontStyle": ""
          }
        },
        {
          "scope": "variable.other.object",
          "settings": {
            "fontStyle": ""
          }
        },
        {
          "scope": "variable.other.readwrite",
          "settings": {
            "fontStyle": ""
          }
        },
        {
          "scope": "support.type.property-name.json.comments",
          "settings": {
            "fontStyle": ""
          }
        }
      ]
    }
  },
```

Should work the same. Otherwise, there should be a migration guide for settings.

**Screenshots**

> With new Material theme:

![Screenshot 2023-12-05 at 11 04 19](https://github.com/material-theme/vsc-material-theme/assets/33042011/4cb7b1da-ae8b-4197-a548-d67bb7c8cdbe)

 
> How it used to look:
<img width="630" alt="Screenshot 2023-12-05 at 10 26 19" src="https://github.com/material-theme/vsc-material-theme/assets/33042011/b218fad2-48b9-441e-9494-829295968bc2">

**Comment by equinusocio** [comment]
Just remove the "Community " from the brackets...

**Comment by MathiasKandelborg** [comment]
I appreciate the quick answer, but the whole point of the issue is that changing the settings I have to the 'new' theme does not change the highlighting in the same way.

> Just remove the "Community " from "[Community Material Theme Darker High Contrast]".

What you state is not helpful, this is what I did, and the syntax still looks different. Did you even read the issue closely? Perhaps you did, but you didn't try to replicate it because you would be able to tell that the colours are different. The whole point of why I made the issue

See the parenthesis in 'To Reproduce' step 1.

Also, I point out that there should be a migration guide since the community extension was deprecated in favour of this extension. Sure, there might be differences, but then there should be a migration guide, as I've also stated in the original issue.

What I'm experiencing is **not** changing the theme name. A clear indicator of this can be seen in the before/after screenshots. The before has Purple for types, which is also somewhat present in the after. 

But look at the keyword `Parse` and tell me if you can see a difference. There is, which shows there's a difference in how the settings work. So, to say it again, there should be a migration guide and not a discussion on Github that does not explain the differences between the deprecated extension and this one which we're now supposed to use; and is not easily searchable. It should be stated on the extension READMEs. I rarely use Github, I guess others migrating also don't - it's fairly common sense to write the information on the extensions themselves

Just to reiterate 'just' make a migration guide. At least write somewhere that people migrating would have to change their settings. But to go all-in would be to explain the differences since there are differences.

I know I repeat myself a lot here. But I hope you realise the points I'm trying to make:

- Make a migration guide for settings
- OR explain that settings are different and show where to find out. This will still waste people's time but at least it's better than having to make an issue on GitHub to find out.

Deprecating an extension for another one that introduces changes should come with a warning, guide (if needed), or at least a statement saying there are differences.


And btw, the issue you linked is not helpful, it does not describe the few changes I have and what they should be going from deprecated to the new extension. I want some explanation of the differences, I didn't choose to deprecate the community extension; people working on the two extensions did. It's not on me, the user, to figure these things out.

**Comment by MathiasKandelborg** [comment]
I could edit my comment but it's already a wall of text. Sorry for the double notification:

I know I'm not the only one not using GitHub regularly. I dislike using discussions to convey changes of this magnitude. Discussions are used for mostly user-to-user interactions, where maintainers/owners can chime in. It shouldn't be a place to tell about deprecations or how to customize a plugin for a text editor.

**Comment by equinusocio** [comment]
Did you disabled semantic highlight?

**Comment by MathiasKandelborg** [comment]
Thank you for the comprehensive answer.

The Discussions page is still not the correct place for the information. There's a wiki, and you have a README that should at least direct users to the relevant topics on the discussions page if you insist on using it for the wrong purpose.

> GitHub Discussions is a collaborative communication forum for the community around an open source or internal project. Discussions are for conversations that need to be transparent and accessible but do not need to be tracked on a project board and are not related to code, unlike GitHub Issues. Discussions enable fluid, open conversation in a public forum.

https://docs.github.com/en/discussions/quickstart#introduction


As a UX designer, I expect that you understand the problems with the experience I, as the user, have. The extension wasn't listed as deprecated before December 1st. How am I to know that I use an obsolete extension when it's there and it doesn't say so anywhere?

I want to thank you for all the work on Material Theme. I love the whole design system and am happy it is integrated into my work environment. I'm mostly talking about the experience, and I am trying to convey how it is confusing and a waste of time to go through all of this when it could have been easily prevented by readily available information.

I'm looking forward to using the new features, and will of course spend the time necessary to utilise the new systems VSCode has. It sounds like a lot of fun to get it all set up how I'd like it. Thanks again for the hard work. I hope people migrating will be able to see these links in the README or described in a wiki, where this kind of information belongs; which is not me being pedantic, it's agreed upon ways of doing things. Having all this info in discussions is not good UX, and I expect more from the Material Theme team.

Have a great Christmas!

**Comment by equinusocio** [comment]
> The extension wasn't listed as deprecated before December 1st. How am I to know that I use an obsolete extension when it's there and it doesn't say so anywhere?

There was a big deprecation statement at the top of the readme since 2020.

> by readily available information.

Which are in our discussions 🥲

---

Said that, this is not an issue but a QA and will be converted as a closed QA discussion.
