### ISSUE TITLE
Syntax coloration highlighting lost

### ISSUE THREAD

**Issue by fugudesign** [material-theme/vsc-material-theme#1289]
Hello,

Until today, i used the VSC "Material Theme" with "Community Material Theme".
But today i did the "migration" suggested on the "Community Material Theme" that actually remove it cause it now is deprecated and unsupported.
The only inconvenience is that since that, i lost a part of my syntax coloration, especially in my React projects…
So my questions are:
Have you already identify this issue?
Do you know a way to get it back without the "legacy" method?
Thks

**Comment by equinusocio** [comment]
Check discussions.

**Comment by equinusocio** [comment]
- https://github.com/material-theme/vsc-material-theme/discussions/1274
- https://github.com/material-theme/vsc-material-theme/discussions/1287
- https://github.com/material-theme/vsc-material-theme/discussions/1283
