### ISSUE TITLE
Add Go format string coloring

### ISSUE THREAD

**Issue by Nico-Mayer** [material-theme/vsc-material-theme#1291]
**Is your feature request related to a problem? Please describe.**
While working with Go, I observed that all Material themes lack string format coloring. For instance, there is no distinct highlighting for string formatting in expressions like fmt.Printf("Value%d", value).

**Describe the solution you'd like**
I would appreciate a solution akin to the default Visual Studio Code theme, where all values prefixed with '%' are highlighted.

**Additional context**
I believe implementing this should be relatively straightforward, given that the default theme already incorporates such features. I would greatly appreciate seeing this enhancement in future updates. I genuinely love the theme – keep up the excellent work! :)

**Comment by equinusocio** [comment]
We added support for `constant.placeholder` tokens in every language, not only go. The color will be red.

![Screenshot 2023-12-10 at 10 59 56](https://github.com/material-theme/vsc-material-theme/assets/10454741/e9b253c9-fafb-4603-8bf4-1b86ff4c9417)


Release on the way.
