### ISSUE TITLE
Highlight component classes with different colors, like in the legacy Community version of this theme

### ISSUE THREAD

**Issue by brady-sewall** [material-theme/vsc-material-theme#1293]
**Is your feature request related to a problem? Please describe.**
I primarily work with Shopify Liquid files and really like how the Community Material theme would highlight component classes (see screenshot below)

**Describe the solution you'd like**
A color differentiation for component classes. For example in `{{ variant.metafields.acf_variant.disclaimer_message }}`, `variant` would be a different color. This makes it really easy to see what type of object the rest is referencing.

**Describe alternatives you've considered**
Using the Community Material Theme, but it's now deprecated.

**Additional context**
Screenshot pointing to examples in the code (Community Material Theme shown)
![image](https://github.com/material-theme/vsc-material-theme/assets/38672484/e7495602-5e69-40eb-8a70-d87198cfd02f)

**Comment by equinusocio** [comment]
Can you post any valid code example?
