### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by boboj1** [material-theme/vsc-material-theme#1296]
less
![image](https://github.com/material-theme/vsc-material-theme/assets/80439498/1687a1aa-9555-4122-9895-9e421ff22af3)

scss
![image](https://github.com/material-theme/vsc-material-theme/assets/80439498/739e2138-031c-4335-8f57-9c35f1394410)

**Comment by equinusocio** [comment]
Syntax highlighting for unsupported languages such as SCSS and LESS ar available through third-party extensions. We just set colors for tokens and we don't have control over which tokens are used across the code.

In any case you can customize any color by using VSC API:
https://github.com/material-theme/vsc-material-theme/discussions/1274
