### ISSUE TITLE
Theme accent doesn't change

### ISSUE THREAD

**Issue by sentreal** [material-theme/vsc-material-theme#1298]
I am using the latest version of the theme on the official branch of VSCode, and the accent colour doesn't change at all.

<img width="578" alt="image" src="https://github.com/material-theme/vsc-material-theme/assets/20587599/3c68a921-4ffb-41ad-9a77-b681f4bd54c4">

**Comment by deverebor** [comment]
This is releated to material icons, not the theme it self. 

![image](https://github.com/material-theme/vsc-material-theme/assets/62480586/3cf72ac3-202f-4467-9431-bc0924ef0aa7)


![image](https://github.com/material-theme/vsc-material-theme/assets/62480586/1c66b265-e6cd-4e5c-b687-c08fb36079ec)

**Comment by equinusocio** [comment]
You are not using the official Material Theme Icons. We don't provide a command "Change folder color"
