### ISSUE TITLE
 Enhance Inlay Hint Visibility

### ISSUE THREAD

**Issue by Nico-Mayer** [material-theme/vsc-material-theme#1300]
**Is your feature request related to a problem? Please describe.**
Currently, in the VSC Material theme, inlay hints do not stand out distinctly from the overall theme. They appear more akin to function arguments to me at the moment. 

**Describe the solution you'd like**
I would recommend enhancing their visibility to clearly differentiate them from function arguments. I suggest making them resemble the style used in JetBrains IDEs, as illustrated in the screenshots.

**Describe alternatives you've considered**
I'm unsure about their level of customization via themes, but I would also appreciate it if they had rounded corners, similar to the context menus in VSC.

** VS Code Inlay Hints**
![image](https://github.com/material-theme/vsc-material-theme/assets/74204544/cbd5ce5a-0527-40d8-a587-bc3f35bbe5fc)

**WebStorm Inlay Hints**
![image](https://github.com/material-theme/vsc-material-theme/assets/74204544/5c75d760-79d8-486c-8840-be17f6479219)

**Comment by equinusocio** [comment]
https://github.com/material-theme/vsc-material-theme/discussions/1274

**Comment by equinusocio** [comment]
https://github.com/material-theme/vsc-material-theme/discussions/1274
