### ISSUE TITLE
Please Recover the Repo History

### ISSUE THREAD

**Issue by antfu** [material-theme/vsc-material-theme#1303]
I am sorry that I sent the tweet before creating this issue first: https://x.com/antfu7/status/1821971204342984740. I hope you won't feel too bad about the negative comments, but I also do wish you knew the outcome when you made that decision.

I do understand how you feel as a maintainer of a popular open source that didn't get paid well by the community. It's tempting to connect the "downloads" and "potential income", and might feel unbalanced. However, I believe open source is about people and community, acting like this is irresponsible for your previous code/financial contributors, and most importantly, would lose the trust of your users and community.

I would kindly ask you to revert the change and recover the damage. I'd be happy to delete my tweet and undo my words to the project if you'd like to take that move.

Thank you, and I am sorry for any bad feelings and inconvenience. I really wish we could have a better OSS community.

**Comment by equinusocio** [comment]
First of all: https://github.com/material-theme/vsc-material-theme/issues/1301

Hi there, just wanted to let you know that we have decided to make Material Theme and Material Theme Icons closed-source and free, but we're considering to make a pay version with new features. We've been open-source for 9 years, but we've encountered several license violations and clones that have affected the credibility and quality of our extension. Also, there haven't been any contributions to our projects in 9 years, so we feel it's time for a change. We hope you understand our decision and we appreciate your (lack of) support.

It's important to remember that individuals and organizations have the freedom to maintain their software as closed-source, especially when there has been no external contributions over a long period of time. Requiring projects to be open-source when there's no active community engagement can be unnecessary and potentially burdensome.

Last but least, issues are now for bug only, next time we'll close it without comments. For discussione, we have the Discussions section.
