### ISSUE TITLE
Awful practices.

### ISSUE THREAD

**Issue by evieluvsrainbows** [material-theme/vsc-material-theme#1309]
Deleting all remnants of when this extension was open source under the Apache2 license and then violating said license by a) resetting the entire git repo and b) disrespecting the prior 93 contributors to your project and their contributions, when their contributions were licensed under, and only, the Apache 2 license, is downright disrespectful, unprofessional, and straight up does not belong in open source.

Additionally, going after Zed, and one of its extension authors, for creating a version of the Material Theme, when you don't even own anything of the theme and use the Material Design language from Google as inspiration, is also unprofessional. I also heard from a Theo (t3dotgg) video that you also basically forced the only actual developer of the extension to stop being a maintainer because you were a major jerk to them. Your theme is not unique. Your theme makes up around 1000 lines of TypeScript. A theme for VS Code is not hard to make, nor is it unique in any way. Threatening to go after a developer in a different ecosystem for creating a Zed-tailored version of your Material-inspired theme, despite it being previously licensed under Apache 2, is also unprofessional.

Everything you have done is awful and is not how an open source member should act or behave. Theo said not to go after you in his video, but this is just terrible behavior from you. I will no longer even consider using your theme anymore, due to this behavior. Do and be better, and I urge you to reinstate the prior version of the extension.

**Comment by dotexe3301** [comment]
Correct! I came from the t3.gg video and I'm glad I never used Material Theme. Making a paid product would be good instead of changing the LICENSE file to get some revenue.

**Comment by mallowigi** [comment]
Well to his defense Murica gives a bad precedent relatively to copyright infringement abuses, it's no wonder people would take inspiration from it.

Also you can't blame him from being shady. The POTUS IS shady and everyone venerates him so...

Now it's only a matter of whether or not he's right according to the law.

**Comment by toiletbowlkuku** [comment]
He has a history of going after open source projects with baseless claims.

https://dev.to/equinusocio/why-you-should-avoid-sublime-text-2c73

**Comment by dotexe3301** [comment]
> He has a history of going after open source projects with baseless claims.
> 
> https://dev.to/equinusocio/why-you-should-avoid-sublime-text-2c73

Many great tools, softwares wouldn't exist if everybody became like him. Even Open-Source wouldn't exist lol.

**Comment by neu-ma-tic** [comment]
I don't want to pile on, but reading some of this guys comments.... he's so hypocritical and constantly does the exact opposite of what he says

happy new year @/equinusocio, hope you can be a happier person in the new year ;)

**Comment by dcw312** [comment]
I came here from Theo’s You Tube video. https://youtu.be/3wz7YF2as-c?si=keI65Z8_b32ADjia I’d like to assume positive intent from @equinusocio   It’s perfectly acceptable to decide to take a project closed source, provided that it’s done in the right way. If there’s a good faith discussion of how to transition and honor the previous license. I’m here for it.
