### ISSUE TITLE
Reviews and Forks are outdated at material-theme.dev

### ISSUE THREAD

**Issue by Zaczero** [material-theme/vsc-material-theme#1310]
### Description

Hello! I noticed that the Reviews and Forks statistics on https://www.material-theme.dev/ are outdated, which could mislead users. Here are my suggestions for improvement:

- Updating the review statistics to reflect current data
- Adding a "Last Updated" date to indicate when the statistics were last refreshed
- Including a direct link to the marketplace where users can verify the latest reviews
- Removing the forks counter, as it may become irrelevant once the extension transitions to a proprietary model
- Revising the "Loved by all" tagline to more accurately reflect user sentiment, perhaps to "Loved by some" or similar phrasing, as current reviews and online discussions show mixed opinions

### Steps to reproduce

1. Go to https://www.material-theme.dev
2. Scroll to "Loved by all" section

### Extension Version

34.7.9

### VSCode Version

N/A

### Theme

None

**Comment by equinusocio** [comment]
loved by all the users, which are over 7 milions.
