### ISSUE TITLE
"Change accent color" has no effect

### ISSUE THREAD

**Issue by CodeW0lf** [material-theme/vsc-material-theme#148]
VSCode 1.22.0-insiders, Material Theme 1.5.1, Windows 10

Color theme is activated and I can change the overall color variant of Material Theme. Changing the accent color reloads the window, but leaves the accent color set to the default (which I assume is Sky). There are no changes to my User Settings after changing the accent color.

**Comment by equinusocio** [comment]
Do you change the accent color with the setting file opened?

**Comment by equinusocio** [comment]
Do you change the accent color with the setting file opened?

**Comment by DartWolf** [comment]
I've ended up trying it both ways (after it wasn't working I opened the settings file to see if changes were being made).

**Comment by coe-comm** [comment]
VSCode 1.21.1, Material Theme 1.5.1, Mac OS High Sierra

Theme won't change from the high contrast versions. I've also tried changing the color variant with and without the settings window open and no luck. I'm able to select the non high contrast versions, but it doesn't do anything.

**Comment by DartWolf** [comment]
Since the latest version of VSCode (see screenshot) the accent color is applying again. It doesn't apply to folders still unless I modify my own User Settings to add (any accent color text):

`"materialTheme.cache.workbench.settings": {
        "accent": "Yellow"
    },`

After changing that line, changing accent color using the menu option will update the folder color and then will continue to work without issue for any other color that I choose (seems similar to #152). Given the oddities with the insiders release I'm not convinced that this is really a problem with theme at all :)

![image](https://user-images.githubusercontent.com/602465/38236324-acd6f510-36d8-11e8-8464-07dc0c84e449.png)

**Comment by equinusocio** [comment]
@DartWolf Any update on this? i can close this issue?

**Comment by DartWolf** [comment]
Yeah, we can close this one. Later versions of VSCode Insider seem to be behaving. Thanks.

**Comment by xh3b4sd** [comment]
I just moved to vsCode and seem to have this problem. The accent appears to stay yellow regardless the configuration. Neither changes to the settings UI nor the JSON file have any effect. No restart helps. My expectation would have been to see the accent somewhere. Maybe the statusbar, cursor or tab highlights, but no luck. Any feedback welcome. 

```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (1 wk ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```


<img width="617" alt="Screenshot 2020-05-26 at 23 15 02" src="https://user-images.githubusercontent.com/552769/82951207-0a563c80-9fa7-11ea-8d93-af9e5ad9f0e8.png">

<img width="445" alt="Screenshot 2020-05-26 at 23 15 20" src="https://user-images.githubusercontent.com/552769/82951211-0b876980-9fa7-11ea-91ac-7bbf3ec0b263.png">

**Comment by xh3b4sd** [comment]
Playing around a little more I could change the accent via the command palette using `Material Theme: Set accent color`. Though the cursor colour may not be part of this feature.

**Comment by equinusocio** [comment]
You can customize it:
https://github.com/material-theme/vsc-material-theme#override-theme-colors

**Comment by xh3b4sd** [comment]
I figured the cursor colour meanwhile. Thank you.
