### ISSUE TITLE
Reset accent color defaults to Blue rather than whatever color was previously active

### ISSUE THREAD

**Issue by carlocardella** [material-theme/vsc-material-theme#287]
**Describe the bug**

**To Reproduce**
1. Start with a theme that sets an accent color (e.g. ```CarloCardella.hogwarts-colors-dark```): tab.ActiveBorder is set to #BD2A1B
2. Set the accent color to any color of your choice. e.g. ```Set Accent Color -> Lime```
3. Now reset the accent color: ```Set Accent Color -> Remove Accents```
4. tab.ActiveBolder (and a number of other settings) are now changed to the Material Theme default accent color (Blue) rather than back to the original #BD2A1B

**Expected behavior**
When resetting the Accent Color, return to the original accent rather than defaulting to Blue

**Screenshots**
Initial state:
![image](https://user-images.githubusercontent.com/5784415/48965218-f1159f80-ef6d-11e8-86d2-68770f266955.png)

Set the Accent to Lime
![image](https://user-images.githubusercontent.com/5784415/48965230-0ee30480-ef6e-11e8-980b-96f8674d9d53.png)

![image](https://user-images.githubusercontent.com/5784415/48965253-549fcd00-ef6e-11e8-812c-d76a77180304.png)

Reset Accents
![image](https://user-images.githubusercontent.com/5784415/48965240-26ba8880-ef6e-11e8-95e8-d20a40a94b34.png)

![image](https://user-images.githubusercontent.com/5784415/48965258-6b462400-ef6e-11e8-85b7-367449624a6d.png)

**Desktop (please complete the following information):**
```
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

**Additional context**
When setting the accent color (.2 above) a number of settings get added to User Settings under ```workbench.colorCustomizations```, then when the Access is reset these same settings are set to Blue rather than being removed from the user configuration. 

```json
"workbench.colorCustomizations": {
    "activityBarBadge.background": "#C6FF00",
    "list.activeSelectionForeground": "#C6FF00",
    "list.inactiveSelectionForeground": "#C6FF00",
    "list.highlightForeground": "#C6FF00",
    "scrollbarSlider.activeBackground": "#C6FF0050",
    "editorSuggestWidget.highlightForeground": "#C6FF00",
    "textLink.foreground": "#C6FF00",
    "progressBar.background": "#C6FF00",
    "pickerGroup.foreground": "#C6FF00",
    "tab.activeBorder": "#C6FF00",
    "notificationLink.foreground": "#C6FF00",
    "editorWidget.resizeBorder": "#C6FF00",
    "editorWidget.border": "#C6FF00",
    "settings.modifiedItemIndicator": "#C6FF00",
    "settings.headerForeground": "#C6FF00",
    "panelTitle.activeBorder": "#C6FF00",
    "breadcrumb.activeSelectionForeground": "#C6FF00",
    "menu.selectionForeground": "#C6FF00",
    "menubar.selectionForeground": "#C6FF00"
 ```

**Comment by LasaleFamine** [comment]
Hi @carlocardella, thanks for reporting this one. I have opened a PR with the fix. We will add this in the next release that will be on store soon.

**Comment by carlocardella** [comment]
Thanks, the update basically works but I think it also creates a secondary potential bug (sorry I didn't mention this case when I initially opened the issue) and also shows an odd behavior. Here's the breakdown: 

#### Bug
1. Say I want to manually customize my theme in my user settings updating ```workbench.colorCustomizations```:
![image](https://user-images.githubusercontent.com/5784415/48993870-12ed5e80-f0f5-11e8-8ae9-8e42f9659d3a.png)
2. Use ```Set Accent Color``` and set a color of your choice
3. Now remove the accent using ```Set Accent Color -> Remove Accents```
4. The custom ```tab.activeBorder``` is removed along with the other accent settings added by Material Theme
![image](https://user-images.githubusercontent.com/5784415/48993994-afaffc00-f0f5-11e8-8ac6-faabe43e6252.png)

#### Odd behavior
When removing the accent color through ```Set Accent Color -> Remove Accents``` I noticed two things happen:
1. A new setting ```materialTheme.accent: remove accents``` is added to my custom settings:
![image](https://user-images.githubusercontent.com/5784415/48994027-dd954080-f0f5-11e8-8053-ee80f5b6bd50.png)
2. The custom settings added when enabling the accent are all removed
3. Now remove ```materialTheme.accent: remove accents``` and save the settings: all the custom settings removed at .2 are added back, this time defaulting to ```Blue```

I understand this may be a tricky situation to deal with, especially the first case where the user manually adds some settings that are also changed when setting the accent: maybe a solution could be to keep track of which of those settings are already set (if any) and restore them when the user calls ```Remove Accents```?

**Comment by equinusocio** [comment]
@LasaleFamine

**Comment by LasaleFamine** [comment]
Really thanks @carlocardella for your detailed explanation. 

> I understand this may be a tricky situation to deal with, especially the first case where the user manually adds some settings that are also changed when setting the accent: maybe a solution could be to keep track of which of those settings are already set (if any) and restore them when the user calls Remove Accents?

This is exactly what we want to do with the new settings handler, but will require more developing time. I will investigate this week on how to fix the problem in a better way. I hope you can still use the theme as you want!

**Comment by carlocardella** [comment]
Yes, I don't change accent colors often and there is an easy workaround so it's not a big deal for me; happy to test it further when you'll have a solution ready

**Comment by equinusocio** [comment]
@carlocardella Right now we are working on #258 #269. Next step this issue. Meanwhile if you have any suggestions we are happy to hear them.

**Comment by equinusocio** [comment]
Hi @carlocardella, we're sorry for this but currently we ha no bandwidth to work on this. We really appreciate a PR, meanwhile we close this due to inactivity
