### ISSUE TITLE
Use the theme accent color to stylize the remote connections button in the gutter

### ISSUE THREAD

**Issue by tristan957** [material-theme/vsc-material-theme#374]
**Describe the bug**
Currently, if you change the theme accent color, the remote connections button that is new with Microsoft's Remote Extension suite is not colored correctly

**To Reproduce**
1. Install the remote extension pack
2. Reload if necessary
3. Switch accent color to a non-default

**Expected behavior**
Color the button with the correct accent color

**Screenshots**
<img width="22" alt="image" src="https://user-images.githubusercontent.com/11936772/61246923-9fe13880-a715-11e9-8ca6-59606454908c.png">

My accent color of choice is lime not teal or whatever color this is.

**Comment by tristan957** [comment]
That's unfortunate

**Comment by equinusocio** [comment]
Sorry, vacations.

**Comment by equinusocio** [comment]
This should be fixed with the new color schemes (#389)

**Comment by tristan957** [comment]
Thanks for your work on this issue.
