### ISSUE TITLE
inconsistent function brackets colors when inside of Template strings

### ISSUE THREAD

**Issue by wlchn** [material-theme/vsc-material-theme#375]
**Describe the bug**
Function brackets colors when inside of Template strings, are colored inconsistently compared to outside of Template strings.

**Versions**
macOS 10.14.3 (18D109)
vscode 1.36.1 (1.36.1)
darker-hc theme, lastest version

**To Reproduce**
Create a `TypeScript` file and copy/paste the following.

```
const func1 = word1 => {
  return word1;
};

// brackets are white
const foo = func1('hello');

// func1's brackets inside of template are green, should be white
const bar = `abcedf() ${func1('hello')}`;
```

**Screenshots**
`func1`'s brackets inside of template are green, should be white
![image](https://user-images.githubusercontent.com/4652410/61875326-f6702300-af1c-11e9-8629-a2048a2391c1.png)

vscode default dark+ theme keeps color same. that's expected.
![image](https://user-images.githubusercontent.com/4652410/61874733-b9eff780-af1b-11e9-9037-5202ca7538e8.png)

**Comment by equinusocio** [comment]
#389
