### ISSUE TITLE
called function not the same color as the defined one in python

### ISSUE THREAD

**Issue by Mocktezuma** [material-theme/vsc-material-theme#376]
**Describe the bug**
When i define a function in python then call it, the called function is not the same color as the defined one (see screenshot). the name is blue in the def but the called function is colored grey. idk if its a bug or a feature of the theme. If its a feature how do i modify the theme to make it act like i want it to ?

**Expected behavior**
def function color same as called function

## Screenshot
![alt text](https://i.imgur.com/wFUiKMT.png "screenshot")

**Additional context**

**Comment by petrosschilling** [comment]
Any updates on this?
I am having the same issue.

**Comment by petrosschilling** [comment]
@Mocktezuma try this is you settings.json for the meantime.

```
"editor.tokenColorCustomizations": {
        "textMateRules": [
          {
            "scope": "meta.function-call.generic.python",
            "settings": {
              "foreground": "#82aaff"
            }
          }
        ]
      },
```

**Comment by Mocktezuma** [comment]
I will try this out, thanks !

**Comment by equinusocio** [comment]
#389
