### ISSUE TITLE
I cant' update or install any extension after updating 

### ISSUE THREAD

**Issue by dev-aboali** [material-theme/vsc-material-theme#382]
Issue Type: <b>Bug</b>

Any time I try to update any extension I get this message => Failed to update 'equinusocio.vsc-material-theme'.

I don't know what I suppose to do? 

Extension version: 29.2.0
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.89GB (1.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by equinusocio** [comment]
We think this can be related to the repository location that was moved under a new org. We'll investigate.

**Comment by equinusocio** [comment]
@dev-aboali is this fixed?
