### ISSUE TITLE
Multiple Discrepancies between Sublime Text & VSCode PaleKnight Theme

### ISSUE THREAD

**Issue by Roblouisck** [material-theme/vsc-material-theme#386]
**Describe the bug**
Recently switched from sublime to vscode and noticed a few differences between Sublime Text's paleknight theme and vscodes paleknight.

- Conditionals like if/else are cyan instead of purple
- No square bracket highlighting
- No mustard highlighting for document

**Sublime Text (Expected behavior)**
 ![image](https://i.imgur.com/DCzX1CT.png)

**VSCode**
![image](https://i.imgur.com/f9KuqPl.png)

**Additional context**

**Comment by equinusocio** [comment]
Hi @Roblouisck. Material Theme for sublime text was dropped some years ago. In the meantime the theme evolved, the syntax and the color schemes were updated. Today we're working on new (second update) official color schemes and the current ones will not be maintained anymore.
