### ISSUE TITLE
HTML tags lose context highlighting after loop in razor pages

### ISSUE THREAD

**Issue by AlphaComposite** [material-theme/vsc-material-theme#387]
- VSCode Version: 1.38.1
- OS Version: 10.14.6 
- Material Theme: Ocean
- Material Theme Version: 30.0.0

**Describe the bug**
When using a loop within an ASP.NET Razor page, the HTML tags lose context highlighting after the loop. 

![image](https://user-images.githubusercontent.com/25360554/66038870-fc394480-e51b-11e9-94c9-a31bea8ad995.png)

**Comment by equinusocio** [comment]
Are you using the correct extension for that language?

**Comment by AlphaComposite** [comment]
Yes.  The standard C# extension provides support for Razor pages.

**Comment by equinusocio** [comment]
#389
