### ISSUE TITLE
Material Theme Lighter does not change terminal (cmder) colors

### ISSUE THREAD

**Issue by AlexandrPogodin** [material-theme/vsc-material-theme#388]
**Describe the bug**
Material Theme Lighter does not change terminal (cmder) colors

**To Reproduce**
1. Install Cmder as integrated terminal
2. Set "Material Theme Lighter" theme
3. Open terminal

**Expected behavior**
Colors change for readability

**Screenshots**
![](https://i.imgur.com/i6ah8w8.jpg)

**Additional context**
On another computer, the old version is cmder, and there the color changes.

**Comment by AlexandrPogodin** [comment]
With Ayu theme color changes

**Comment by AlexandrPogodin** [comment]
Color does not change at all. Do as in Ayu theme

**Comment by equinusocio** [comment]
Hi @AlexandrPogodin , I'm sorry but  we don't support other extensions integrations.

**Comment by AlexandrPogodin** [comment]
Can you change the color of the terminal so that the text is readable?

**Comment by equinusocio** [comment]
The integrated terminal is working as expected, as we said we don't support third-party tools.

<img width="739" alt="Screenshot 2019-10-16 at 13 36 37" src="https://user-images.githubusercontent.com/10454741/66915757-1abe3600-f01a-11e9-923d-f81b7c4c92ff.png">
