### ISSUE TITLE
Color Theme Clarification?

### ISSUE THREAD

**Issue by hl2guide** [material-theme/vsc-material-theme#394]
Could you please consider making it clear what Color Themes are included before a user downloads and installs the extension?

Currently the website "https://material-theme.site" has one preview but with no names.

Specifically: Darker, Lighter, Palenight and Ocean:
![1](https://user-images.githubusercontent.com/17044982/69121395-5e600000-0af0-11ea-836a-b5990bfce23d.png)

Please consider full preview images with clear titles (names).

Thanks for your awesome work 👍

**Comment by equinusocio** [comment]
We are planning to release a new website for the release of the new themes.

**Comment by sellsjonathan** [comment]
Hmm, honestly this was a little shocking to me.  I always loved how the, now, legacy themes separated elements of the syntax. It's gotten so much less specific. I hope legacy themes don't go away - or the new ones get expanded.

**Legacy Pale Night**
![image](https://user-images.githubusercontent.com/8787299/71857678-64b53600-30b6-11ea-96cd-cc76c2f35cf1.png)

**New Palenight**
![image](https://user-images.githubusercontent.com/8787299/71857704-7dbde700-30b6-11ea-8dd5-10dc1c1d4934.png)

**Comment by equinusocio** [comment]
Closed in favour of #416
