### ISSUE TITLE
Two background colors in editor

### ISSUE THREAD

**Issue by minhduc0711** [material-theme/vsc-material-theme#395]
**Describe the bug**
There are two background colors in the editor window, and I'm not talking about the current line highlight color.

**To Reproduce**
Select Material Theme Ocean High Contrast

**Expected behavior**
There should be only one background color

**Screenshots**
![bug](https://user-images.githubusercontent.com/34294427/69293896-c7ed2500-0c3c-11ea-911a-40ec48762720.png)

**Additional context**
It also happens in Palenight theme.
I'm using VSCode 1.40.1 on Ubuntu 18.04.3

**Comment by equinusocio** [comment]
What!? This is really weird. We don't set multple backgrounds color. We set just one background with one theme key. It looks like a compression/rendering issue caused by vscode :/

**Comment by minhduc0711** [comment]
@equinusocio You're right, it's a vscode problem.
I've disabled all extensions and switch to the built-in theme Tomorrow Night Blue. It looks even worse here.

![bug](https://user-images.githubusercontent.com/34294427/69350056-73cd5980-0cab-11ea-80a3-8ce8fc1b8121.png)
