### ISSUE TITLE
White text on white background for Material Theme Lighter on 31.1

### ISSUE THREAD

**Issue by anmead** [material-theme/vsc-material-theme#409]
**Describe the bug**
The text colors for the close button on editor tabs and some headers in Material Theme Lighter are white and not visible (see screenshot) for the latest update `31.1`

**To Reproduce**
For extension text:
1. Change your theme to `Material Theme Lighter` or `Material Theme Lighter (High Contrast)`
2. Find an extension in the marketplace.
3. Click on one.
4. Notice how the header / description / etc is white and unreadable.

For close buttons:
1. Change your theme to `Material Theme Lighter` or `Material Theme Lighter (High Contrast)`
2. Open a file.
3. Notice how the close button that should be on the tab is not or hardly visible.

**Expected behavior**
The text on extension pages and the close button should be legible.

**Screenshots**
![screenshot](https://i.imgur.com/7qzkss2.png)

**Additional context**
Thanks for the awesome theme tho! :) Been using it for so long.

**Comment by equinusocio** [comment]
Thank you. Does it occurs even with other light themes?

**Comment by anmead** [comment]
It seems the same dark font color is used for other light themes that are included with VSCode. Some other themes have a dark font selected as well.
![lighttheme](https://i.imgur.com/jN4uBgu.png)

**Comment by ospfranco** [comment]
Also experiencing this, thanks a lot for the theme though! :)

**Comment by equinusocio** [comment]
This should be fixed with the latest release
