### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by jhpratt** [material-theme/vsc-material-theme#411]
The Twitter account you linked in #410 has 14 followers. The theme has 1.6 million installs on VS Code. It hardly seems reasonable that the justification for changing the themes is that.

Is there any particular reason a new release was not created, such that a release notes popup was caused, indicating the potential for future changes and request for feedback? That would have given _tens of thousands_ of people (at the least) an opportunity to participate, rather than the 14 followers you have on Twitter and 23 people watching this repository.

As you mentioned,

> This change is introduced to solve many other issue related to the schemes maintainability since old schemes and builder were too old and buggy. The new introduced generator allow us to improve, update and fix schemes more easily and with less time. We also wanted to simplify schemes scopes declarations, so this drove us to completely redesign schemes.

Was/is it possible to use the same colors as before? If not, why?

I imagine 99.99% of people _do not care_ how the theme is generated, they just care how it looks.

Please do not lock "discussions" where you respond once and don't address the most basic of concerns. Closing it and marking it "invalid" is inconsiderate of feedback at best.

**Comment by IsaacLf** [comment]
@jhpratt Wow, you're so right, most people (me included) are looking the prettiest color scheme; it would really be disappointing that all we know and all we're used to, changes in a second, just like this.

Normally, when important changes are going to be implemented, you should try to affect the less to the users, e.g let's say that VSCode changes the whole structure of its project (like the way of develop extensions, etc.); before they deploy the app, they ask themselves the impact it will have on the users, to avoid these kind of situations.

And very important, they wouldn't deploy something is not finished yet, and wouldn't announce that the old thing is going to be deleted soon, either. It would only scandalize the whole community.

**Comment by LasaleFamine** [comment]
Hi @jhpratt thanks for your feedback.

I think you can use the legacy theme, don't you? What's the real problem here? The lack of communication? We have been tried hard to get people known what we were doing, maybe we didn't do it the right way, but I'm also thinking we are two developers working hard for making the theme more versatile, maybe we can get some help from the community about this? 

The changes we made to the color schemes were made also to give a new fresh look to the theme. You don't like it, I get it, but you can still use the old schemes, is this a problem for you?

**Comment by maclockard** [comment]
> You don't like it, I get it, but you can still use the old schemes, is this a problem for you?

@LasaleFamine the release notes directly contradict this. The notes said the legacy theme will be deprecated and no longer maintained. If you were still maintaining it, this would be a minor problem and I personally wouldn't care about it. Telling people to just use the old themes and actively deprecating them is doing one thing and saying another.  

99% of the reason I was using this vscode extension was how well it paired the syntax highlighting with the editor color scheme. To completely change how how the syntax highlighting looks is very unfortunate and removes the reason I installed the extension in the first place.

If you were personally unsatisfied with the "legacy" syntax highlighting, I understand introducing a new scheme and encouraging folks to use it, but deprecating the syntax highlighting scheme people installed and swapping it out will most likely upset many folks.

**Comment by equinusocio** [comment]
@IsaacLf 
> Normally, when important changes are going to be implemented, you should try to affect the less to the users, e.g let's say that VSCode changes the whole structure of its project (like the way of develop extensions, etc.); before they deploy the app, they ask themselves the impact it will have on the users, to avoid these kind of situations.

Are you really comparing a whole team that work for a multinational corporation with us, a team composed by **2 people** that work on this project **for free**, **for everyone**, **in their spare time**?. This is a waste of time, please use another theme if you don't want to use old schemes (that will not be deleted soon)

---

@jhpratt 

> This change is introduced to solve many other issue related to the schemes maintainability since old schemes and builder were too old and buggy. The new introduced generator allow us to improve, update and fix schemes more easily and with less time. We also wanted to simplify schemes scopes declarations, so this drove us to completely redesign schemes.

> Was/is it possible to use the same colors as before? If not, why?

Your "Why " is described inside the lines you quoted.

> I imagine 99.99% of people do not care how the theme is generated, they just care how it looks.

99% of people don't care also that it's a free open-source project which no one ever collaborated on
