### ISSUE TITLE
Disable writing to extension installation directory

### ISSUE THREAD

**Issue by FruitieX** [material-theme/vsc-material-theme#414]
It seems like vsc-material-theme tries to write a user.material-theme.config.json to the extension installation folder.

Can there be a toggle to skip this behavior? Depending on how vscode & extensions are installed, this path may be read-only (such as on NixOS) which produces the following error at vscode launch:

**Screenshots**

![image](https://user-images.githubusercontent.com/3673134/71896724-33dc0c00-315d-11ea-9d84-e61c8fa852d4.png)

**Comment by LasaleFamine** [comment]
Hi @FruitieX and thank you so much for reporting this one. 

This case was actually not covered although initially I thought could happen: we need that config to manage our internal params so we need to find a way to save this JSON.

I don't know NixOS, is it possibile to save the config somewhere within the filesystem? Maybe something like `~/.config`?

**Comment by FruitieX** [comment]
Yeah, `~/.config` is writable for me and would work.

**Comment by LasaleFamine** [comment]
Alright, I think that's a pretty good solution for everyone. Hopefully we will have the fix on the next release (we are releasing a lot in these days...). Thanks for the feedback!

**Comment by equinusocio** [comment]
@LasaleFamine
