### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by equinusocio** [material-theme/vsc-material-theme#416]
Since we trust our community, we need help to make the new home of this theme.

**Comment by mallowigi** [comment]
What help exactly? You can make a site using Wordpress, Gatsby or Jekyll, amongst others.

**Comment by equinusocio** [comment]
We are open to collaborations. We need a designer and a developer who can work on it. But first we need to discuss about what kind of site this theme deserve.

**Comment by JonathanTroyer** [comment]
@equinusocio I would probably recommend using [GitHub pages](https://pages.github.com) for the [material-theme organization](https://github.com/material-theme). If you want to make the repo I can do a PR that simply reflects the current site (with updated assets to show the new theme).

**Comment by mallowigi** [comment]
What I could do, also, would be to use my existing website about the Material Theme plugin for Jetbrains, https://www.material-theme.com/, to also include the VSC plugin. I was already thinking of doing something similarly to this: https://draculatheme.com/, where every other port would have its own page. 

Or you can fork the repository and publish a VSC version of the site, in your own domain.

**Comment by equinusocio** [comment]
Hi @mallowigi, we appreciate your suggestion, but Material Theme for jet brains is born from Material Theme, not vice versa, and now it's an independent project who share only the same name.  They are now totally unrelated, and since Material Theme is the main and original theme, the website should be something more general who shows every port, starting from the vscode one, while your site is focused on the jetbrains version.

--- 

@JonathanTroyer we think a static site deployed on Zeit (our material-theme.site host) through now.js it better because we can configure it on MR and different branches. You want to contribute to the website, we can add you as contributor to the repo. Your proposal can be a nice starting point, if you agree let's continue on the website repository.

**Comment by JonathanTroyer** [comment]
Coolio! I'll work on a PR today.
