### ISSUE TITLE
What happened to the legacy Material Palenight Theme?

### ISSUE THREAD

**Issue by keith0305** [material-theme/vsc-material-theme#417]
I grew fond of the theme. Love it. But a few hours ago, I restarted VSCode and was dismayed to find a completely different color scheme - without me changing any settings.

Okay, so eventually I found that what I was looking for got renamed to "legacy - something". However, it is still not what it used to be.

Here is a screenshot for reference of how it used to be (HTML syntax):
![image](https://user-images.githubusercontent.com/5112337/71917108-4afd1700-31ba-11ea-9f22-ee8b1941c968.png)
_This is how I want it_

And this is how the legacy version of it looks like:
![image](https://user-images.githubusercontent.com/5112337/71917542-45ec9780-31bb-11ea-8318-e5a023007ce5.png)

And the current version that replaced it:
![image](https://user-images.githubusercontent.com/5112337/71917591-6157a280-31bb-11ea-9b04-bb0c19852800.png)

My question is what happened to the theme? Why change it without warning to the users?

**Comment by equinusocio** [comment]
No changes, there was an issue with our new generator. We released old legacy schemes.
