### ISSUE TITLE
New red color in many places is no so great 

### ISSUE THREAD

**Issue by bierbaumtim** [material-theme/vsc-material-theme#418]
With the latest changes you have added the color red in many places where it is really ugly imo and has nothing to do with material design. Please give us the opportunity to change the color red with a single setting or to undo the changes. It would be nice if you could include every place with a corresponding setting name in the changelog.

But most of all I like your themes and I've been using them for 2 years or so

**Comment by vertisan** [comment]
+1
How to restore old color scheme (before update)?

**Comment by GabrielAnca** [comment]
There's a discussion that explains this change here: https://github.com/material-theme/vsc-material-theme/issues/412

You can still switch to the previous color theme (they all have `Legacy` in front of them)

**Comment by andrewjrhill** [comment]
The fact that #412 was closed, limited and marked as spam is a bit unreal. The so-called "complaints" and examples are legitimate feedback. A user base should be allowed to freely and openly voice their concerns.

@equinusocio - Dismissing and silencing your users simply undermines all the work you have done to date is a surefire way of losing the income you are generating from this body of work.

**Comment by equinusocio** [comment]
@andrewjrhill It was a flame (#417 #415 #413 #412 #411 #410) all full of people complaining about new schemes with no proposal, suggestion, or useful contribution. Just people asking to not delete old schemes instead of improving the new one. 

Then finally, you should check also #420
