### ISSUE TITLE
Remove/Disable shadows on New Material Lighter Theme

### ISSUE THREAD

**Issue by gencer** [material-theme/vsc-material-theme#419]
New Material Lighter theme has shadows in sidebar and editor. I can manually remove them using css-hack but wanted to ask if there is an on/off switch somewhere to disable all of these shadows. Legacy doesn't have such shadows.

**See**:

![image](https://user-images.githubusercontent.com/1711576/71938062-4b4be100-31bf-11ea-8b77-bfa77c435192.png)

**Comment by equinusocio** [comment]
The shadows have always been there. You can disable them locally through your settings:

```json
"workbench.colorCustomizations": {
	"[Material Theme Lighter]": {
		"scrollbar.shadow": "#00000000",
	}
},
```

For more info check our readme section about [customising Material Theme](https://github.com/material-theme/vsc-material-theme#color-scheme-override)
