### ISSUE TITLE
Incorrect HTML syntax highlight on Legacy Darker High Contrast

### ISSUE THREAD

**Issue by AntuV** [material-theme/vsc-material-theme#422]
**Describe the bug**
Legacy Material Theme Darker High Contrast HTML syntax highligth is not the same as before 

**To Reproduce**
1. Select "Legacy Material Theme Darker High Contrast"
2. Open any HTML file. Colors are a bit "off".

**Expected behavior**
Colors should be the same as in the "Legacy Material Theme Darker" theme.

**Screenshots**

Legacy Material Theme Darker High Contrast
![Legacy Material Theme Darker High Contrast](https://user-images.githubusercontent.com/47358364/71975837-b9aa9680-31f3-11ea-9d98-ddeda4cb05db.png)

Legacy Material Theme Darker
![Legacy Material Theme Darker](https://user-images.githubusercontent.com/47358364/71975859-c7601c00-31f3-11ea-9ece-874297dcdce8.png)

**Comment by AntuV** [comment]
#421

**Comment by AntuV** [comment]
Downgrading to 30.0.0 worked for me. Gonna check last version every week.

**Comment by evaera** [comment]
Why did you close this? This is still a problem.

**Comment by equinusocio** [comment]
We've fixed this but not yet release @evaera. We can reopon it until the release.

**Comment by AntuV** [comment]
Thanks and sorry for closing it. I misread the issue title, thinking it was duplicated.

**Comment by equinusocio** [comment]
@AntuV can you check with the latest release?

**Comment by AntuV** [comment]
@equinusocio Awesome!

![2020-01-08 23-47-04](https://user-images.githubusercontent.com/47358364/72033563-69721980-3271-11ea-90f2-1f6b72a45470.png)
