### ISSUE TITLE
Ruby syntax highlighting for Palenight inconsistent with legacy version

### ISSUE THREAD

**Issue by JoseFarias** [material-theme/vsc-material-theme#424]
**Describe the bug**
Ruby syntax highlighting for Palenight is not the same as before. I think this might be unintended, as I feel previous highlighting was more comprehensive.

**To Reproduce**
1. Open VS Code
2. Open a Ruby file
3. Switch between **Material Theme Palenight** and **Legacy - Material Theme Palenight** color themes

**Expected behavior**
Syntax highlighting should be the same for both color themes.

**Screenshots**
Ruby syntax highlighting using **Legacy - Material Theme Palenight**
![image](https://user-images.githubusercontent.com/31393016/71999901-d4870600-3207-11ea-9a48-0e86cb1f6027.png)

Ruby syntax highlighting using **Material Theme Palenight**
![image](https://user-images.githubusercontent.com/31393016/71999876-ca650780-3207-11ea-8f60-c79fcebb7b1c.png)

**Additional context**
This is similar to #422

**Comment by equinusocio** [comment]
Hi, next time search for similar issues. As told many times new schemes doesn't look as the old ones and this is intentional. Thank you.

**Comment by JoseFarias** [comment]
Dully noted.
I understand new schemes might not look like the old ones and colors might change. But I feel like having a new scheme where readability is not as good as the old one is a step backwards.

Thank you for working hard to improve these schemes. Hopefully this will worked on in the future, as I very much enjoy the readability, as you put it, of the legacy template.

Sadly, I'm not capable of submitting a PR myself. But I just thought I'd bring this to your attention.

**Comment by y-spreen** [comment]
So you agree that work should be done here

> improve new schemes readability, but this require time and more people

So why close the issue? You can keep an issue open and add the tag "help wanted"

**Comment by equinusocio** [comment]
Because there is no issue related to ruby languages. Schemes uses global scopes and the fix should be done inside our generator (which is used by material theme) as external dependencies. We don't want to left open every single issue about small color changes for every languages.

**Comment by y-spreen** [comment]
Do you have a link for that generator?

**Comment by equinusocio** [comment]
https://github.com/moxer-theme/code-theme-generator

**Comment by equinusocio** [comment]
Then, as told in other issues, we don't want to make new schemes looking like the old ones. We know they're different and that's intentional. The new ruby highlight still good since almost all the tokens use the same colors, but this doesn't make it "unusable", "horrible" or "unusable".

**Comment by y-spreen** [comment]
I think it's still fair to assume that multiple colors are intended for code highlighting color schemes, but these are just opinions. Let's let the community decide?

I think if you closed this issue because of technical issues let's continue in https://github.com/moxer-theme/code-theme-generator/issues/3

**Comment by JoseFarias** [comment]
These comments and the provided links paint a clear picture that fixing this issue carries many implications.

With this knowledge I do see how there are other related closed issues that I might have missed, not knowing what I was looking for.

But, at the same time, the existence of these issues seems to indicate that this is something worth looking at. Given that various members of the community seem concerned with this, including @y-spreen and myself.

It would be great if this got looked at. But if it's simply not a priority then that's fair enough. This issue does render the theme 'unusable' for me. Which is, certainly, an opinion.
