### ISSUE TITLE
CSS, SCSS incorrect color for class name and properties

### ISSUE THREAD

**Issue by betorobson** [material-theme/vsc-material-theme#425]
Describe the bug
Material Theme High Contrast CSS/SCSS syntax highlight show same color for class name and properties.

To Reproduce

Select "Material Theme High Contrast"
Open any CSS or SCSS file. Class name color and properties are using same color.

Expected behavior
Colors for class name and properties should not be the same.

Screenshots:
![Screen Shot 2020-01-08 at 15 40 32](https://user-images.githubusercontent.com/13212208/72006591-bc76ad00-322e-11ea-93dd-4233a80554b6.png)

classes: .group, .group3
properties: flex-direction

Are both yellow :(

**Comment by equinusocio** [comment]
This should be fixed with the latest release.
