### ISSUE TITLE
Python `self`

### ISSUE THREAD

**Issue by y-spreen** [material-theme/vsc-material-theme#427]
Sure, colors are up to taste. And as long as syntax highlighting still does highlighting, I'm fine with your choices.

But self is probably the most important keyword in any member function in python and it is not highlighted at all anymore. I'd consider that a bug?

**Comment by y-spreen** [comment]
I literally re-installed vscode because I'd never have guessed that this huge theme would just make such a huge change without any notice. And then it took me a really long time to figure this out even I did suspect the theme update b/c it's not even a github release.

My suggestion would be to revert the theme and use the new ones as 'New <theme>' instead of the other way around with 'Legacy <theme>'.

That way my experience with the update would have been really great :)

**Comment by equinusocio** [comment]
We can't reproduce this issue. The `self` key has the correct `variable` scope and has the correct color.

<img width="349" alt="Screenshot 2020-01-09 at 20 03 45" src="https://user-images.githubusercontent.com/10454741/72096788-3edc9b00-331b-11ea-845f-24b879abeecc.png">

**Comment by equinusocio** [comment]
> My suggestion would be to revert the theme and use the new ones as 'New ' instead of the other way around with 'Legacy '.

Nope. The only option is improve new themes. Legacy themes are not official anymore. BTW we're working on improving the python support.
