### ISSUE TITLE
Namespaces and keywords not highlighted in C++

### ISSUE THREAD

**Issue by Omegastick** [material-theme/vsc-material-theme#428]
In the recent update, C++ syntax highlighting has regressed.

"Legacy" scheme:
![old_scheme](https://user-images.githubusercontent.com/17452111/72029571-b681da00-32c9-11ea-8bd8-3cf7f6293dca.png)
Latest update:
![new_scheme](https://user-images.githubusercontent.com/17452111/72029575-b8e43400-32c9-11ea-864e-ed61dbf441d1.png)

PS. What happened to other issue with everyone's regressions? There was a lot of valuable information there.

**Comment by equinusocio** [comment]
Please provide additional informations:

- Valid code snippet
- Language extensions used

**Comment by equinusocio** [comment]
Fixed in upcoming release
