### ISSUE TITLE
Punctuation prominence (RFC)

### ISSUE THREAD

**Issue by dustypomerleau** [material-theme/vsc-material-theme#429]
Thanks for creating this great extension. I'm sorry that some users have been spraying hate lately, there's no place for that in open source.

I do think that it's worth having a discussion about certain design decisions in the new themes—the most significant change being the decision to let punctuation move to the background. One of the things that drew me to this theme initially was the way punctuation highlighted each block of code so clearly. The issue isn't so much the exact color of the punctuation, but whether or not it stands out from the surrounding text. By way of example, have a look at some Clojure:

### Legacy theme:

![Legacy](https://i.imgur.com/vUvzN9w.png)

### Current theme:

![Current](https://i.imgur.com/IXFbp9i.png)

I find the Legacy much more readable. Do you agree? Can we achieve something similar with the new themes?

**Comment by equinusocio** [comment]
I can you provide additional informations?

- code snippet
- language
- language estensions used

Thank you

**Comment by dustypomerleau** [comment]
The code snippet is from [this file](https://github.com/clojure/clojure/blob/master/src/clj/clojure/core.clj), and is shown with the default TM scopes (no extension). Since most of the Clojure extensions have rainbow parens I thought that would confuse matters. Thanks.

```clojure
(defn vector
  "Creates a new vector containing the args."
  {:added "1.0"
   :static true}
  ([] [])
  ([a] [a])
  ([a b] [a b])
  ([a b c] [a b c])
  ([a b c d] [a b c d])
	([a b c d e] [a b c d e])
	([a b c d e f] [a b c d e f])
  ([a b c d e f & args]
     (. clojure.lang.LazilyPersistentVector (create (cons a (cons b (cons c (cons d (cons e (cons f args))))))))))
```

**Comment by equinusocio** [comment]
Fixed in upcoming release

**Comment by dustypomerleau** [comment]
Excellent, thank you for your time.

**Comment by equinusocio** [comment]
You're welcome!
