### ISSUE TITLE
Change non-keyword text color on lighter theme?

### ISSUE THREAD

**Issue by ospfranco** [material-theme/vsc-material-theme#430]
First of all thanks a lot for the theme it is really great.

I like light interfaces, I do have a problem however with the material one and that is that the non-keyword text is too light against the white(ish) background, I've been trying to customize it and change it but I'm not having success, could you point out how can I achieve this?

![Screenshot 2020-01-09 at 09 47 18](https://user-images.githubusercontent.com/1634213/72052360-55580780-32c5-11ea-957a-c4d470f87602.jpg)

Some of the settings I've been playing with:

```
  "editor.tokenColorCustomizations": {
    "[Material Theme Lighter High Contrast]": {
      "textMateRules": 
      [
          {
              "scope": "string",
              "settings": {
                          "foreground": "#FF9900" ,}
          }
      ]
    },
  }
```

Thanks a lot!

**Comment by equinusocio** [comment]
If you want to change only the "databse" string (variable parameter), replace the scope with this `variable.parameter`

If you want to change the overall non-highlighted color, use this scope `foreground`

**Comment by ospfranco** [comment]
Thank you! it seems to be partially working:

![Screenshot 2020-01-09 at 10 59 59](https://user-images.githubusercontent.com/1634213/72057804-49714300-32cf-11ea-9bf7-b07ff4071499.jpg)

`variable.parameter` didn't seem to work, just `variable` does change it how I want it, unfortunately `foreground` doesn't seem to be working at all, attached a screenshot.

**Comment by equinusocio** [comment]
@ospfranco Is this issue still present?

**Comment by ospfranco** [comment]
Yes, I did not manage to change it, not sure if it really is an issue though, it is only my personal preference

**Comment by equinusocio** [comment]
👍
