### ISSUE TITLE
awaiting `extensionManager.init()`

### ISSUE THREAD

**Issue by equinusocio** [material-theme/vsc-material-theme#431]
I'm running Arch Linux and have installed VSCode from the AUR.

For me it looks more like you have a possible race condition. In your `core/extension-manager.ts` you call in the constructor `this.init()`. But init is an async function so your exported ExtensionManger (which you use in `material.theme.config.ts` to access firstInstall) does not necessarily everything correctly initialized because init has not finished.

I did a quick test and awaiting `extensionManager.init()` (need to make it public) before line 13 of `material.theme.config.ts` seems to fix the problem.

_Originally posted by @eigoor in https://github.com/material-theme/vsc-material-theme/issues/381#issuecomment-572497425_

**Comment by Hanif1601** [comment]
Visual Studio Code bug, I guess?
