### ISSUE TITLE
Improve PERL support

### ISSUE THREAD

**Issue by joshuabeny1999** [material-theme/vsc-material-theme#432]
**Describe the bug**
The new theme has in perl a lot of white syntax and the Variables are not readable anymore in any programming language. White is for me equals to no syntax highlight available. 

I use no specific language extension for Perl. It is the native perl language

I used the Material Darker High Contrast Version of the Theme. 

**To Reproduce**
1. Open a new File in VS-Code
2. Paste following code snipped in the Editor
3. Change language mode to Perl (CMD+P and then ">Change Language Mode")
4. You see the code syntax highlighted

```perl
#!/usr/bin/perl
#
use warnings;
use strict;
$|++;
use DBI;
use File::Basename;
use Text::Iconv;

use Kernel::System::CustomerUser;
use Kernel::System::CustomerGroup;

my $CustomerUserObject = Kernel::System::CustomerUser->new(
    ConfigObject => $ConfigObject,
    LogObject => $LogObject,
    DBObject => $DBObject,
);
my $CustomerGroupObject = Kernel::System::CustomerGroup->new(
    ConfigObject => $ConfigObject,
    LogObject => $LogObject,
    DBObject => $DBObject,
);

my $converter = Text::Iconv->new("utf8", "windows-1252");

my $DoChange = 0;

sub PrintHelp() {
    print "tA-dbsynchro.pl - synchronize InventoryUsers and Projects to OTRS\n";
    print "  --help     this here\n";
    print "  --change   actually change the db\n";
    print "  --dry-run  dry run - no changes are beeing made\n";
    exit(0);
```

**Expected behavior**
***Language specific:***
- ConfigObject, LogObject, DBObject in this example should have another color than white. This could be green as before, blue/lila or any color you like.

***Not  language specific:***
- That the Variable Prefixes ($, @, %) have another color. Could be also just light grey instead light blue or any other color)
- The "\n" and other \ code should have another color than white. Also the double quotes should have another color than the text inside it. That make it more readable

**Screenshots**
***Current Theme:***
![Screenshot 2020-01-08 at 13 17 22](https://user-images.githubusercontent.com/55023662/72079285-eac1be80-32fa-11ea-8039-c61169d79710.png)
***Lecacy Theme:***
![Screenshot 2020-01-08 at 13 18 05](https://user-images.githubusercontent.com/55023662/72079286-eac1be80-32fa-11ea-88a8-4a66942379dd.png)

**Comment by equinusocio** [comment]
Continue on https://github.com/moxer-theme/code-theme-generator/issues/4
