### ISSUE TITLE
How to disable the new update notifications every time I open VSCode?

### ISSUE THREAD

**Issue by corysimmons** [material-theme/vsc-material-theme#433]
I've added `"update.showReleaseNotes": false` to my settings but just got another notification.

I know this isn't necessarily Material Theme's responsibility but I get these notifications almost daily from this extension and just wanted to confirm you were actually releasing almost daily updates.

**Comment by equinusocio** [comment]
Try `"update.mode": "default" | "start" | "manual" | "none"`

**Comment by corysimmons** [comment]
Hmm. Nah I want the updates. Ah well. I'll just ignore it and hopefully everything will level out after a while.

>People are flaming you guys? Yikes. Love your theme and thanks for the work.
