### ISSUE TITLE
Component's props in React are the same color as component tag

### ISSUE THREAD

**Issue by sasa95** [material-theme/vsc-material-theme#434]
**Describe the bug**
Component's props names in React are the same color as component tag. 
**Edit**: I'm using styled components

**Screenshots**
<img width="491" alt="Screenshot 2020-01-10 at 12 52 57" src="https://user-images.githubusercontent.com/13697709/72151328-39796200-33a8-11ea-962a-ef9acfc78140.png">
<img width="507" alt="Screenshot 2020-01-10 at 13 17 08" src="https://user-images.githubusercontent.com/13697709/72152534-90cd0180-33ab-11ea-8821-3f1b3b6184b4.png">

**Expected behavior**
Props names should have different color just like in Legacy Material themes:

**Screenshots**
<img width="496" alt="Screenshot 2020-01-10 at 12 56 01" src="https://user-images.githubusercontent.com/13697709/72151469-970dae80-33a8-11ea-8116-aacf672ae6c6.png">

**Comment by equinusocio** [comment]
Your syntax looks completely messed up. That's how material theme highlight react code using the proper language extension:

<img width="1000" alt="Screenshot 2020-01-10 at 13 11 20" src="https://user-images.githubusercontent.com/10454741/72152237-b4437c80-33aa-11ea-837a-f334b8f1c730.png">

**Comment by equinusocio** [comment]
See related.
