### ISSUE TITLE
Typescript - Property and type have the same color inside constructor

### ISSUE THREAD

**Issue by sasa95** [material-theme/vsc-material-theme#435]
**Describe the bug**
In typescript, property and type have the same color inside constructor.

**Problem**
<img width="387" alt="Screenshot 2020-01-10 at 15 24 32" src="https://user-images.githubusercontent.com/13697709/72159755-5d936e00-33bd-11ea-82b0-59b3f174a148.png">

**Expected behavior**
<img width="391" alt="Screenshot 2020-01-10 at 15 24 45" src="https://user-images.githubusercontent.com/13697709/72159808-7a2fa600-33bd-11ea-9395-92b9046e8531.png">

**Comment by equinusocio** [comment]
Please provide the snippet.

**Comment by sasa95** [comment]
``` Typescript
import { MatDialog } from "@angular/material/dialog";
import { NgxSpinnerService } from "ngx-spinner";
import { Router, ActivatedRoute } from "@angular/router";

export class BannersComponent {
  constructor(
    private dialog: MatDialog,
    private spinner: NgxSpinnerService,
    private router: Router,
    private route: ActivatedRoute,
  ) {}
}
```

**Comment by equinusocio** [comment]
@sasa95 This issue should be fixed, can you confirm?

**Comment by sasa95** [comment]
Confirmed. Thank you.
