### ISSUE TITLE
Color scheme is different on PC and laptop

### ISSUE THREAD

**Issue by anhnt9996** [material-theme/vsc-material-theme#436]
**Describe the bug**
I installed Material theme on my PC and laptop, i use save settings, color theme and lastest version but i don't know why it display 2 color scheme. It happend after i updated to lastest version. I want it display color scheme like my PC.

**Screenshots**
My PC:
![81749510_521200315160562_6779418371348758528_n](https://user-images.githubusercontent.com/30967513/72166323-96523800-33fb-11ea-87a8-b0fd41519651.png)

And my laptop (wrong color :(()
![Screenshot_1](https://user-images.githubusercontent.com/30967513/72166345-a36f2700-33fb-11ea-8c59-267cb117006c.png)

**Comment by equinusocio** [comment]
You're using two different version of the theme. The one in the second screenshot is the last one, we shipped many syntax fixes to improve readability.

**Comment by anhnt9996** [comment]
> You're using two different version of the theme. The one in the second screenshot is the last one, we shipped many syntax fixes to improve readability, in this case, we differentiate JSX/React components from html elements. 👍

i just install version 31.12.0 same as my PC but still display different color, i really really want to use this color because its familiar to me
![Screenshot_1](https://user-images.githubusercontent.com/30967513/72167669-242f2280-33fe-11ea-93fd-9ec04c1213e8.png)

**Comment by equinusocio** [comment]
We can't help you, this issue is not related with the theme. Are you sure you're using the same react extensions on both computer?

**Comment by anhnt9996** [comment]
> We can't help you, this issue is not related with the theme. Are you sure you're using the same react extensions on both computer?

It's ok, i just custom some scope in settings.json and it's work :D. Thanks!
