### ISSUE TITLE
Community Material Theme

### ISSUE THREAD

**Issue by equinusocio** [material-theme/vsc-material-theme#437]
![mt-community](https://user-images.githubusercontent.com/10454741/72192124-c81bcc80-3404-11ea-82de-fbf70a250ffa.jpg)

## Overview

Since we're not able to maintain 20 color schemes, we decided to deprecate and then delete — probably next year — the old legacy schemes. If you want to help we can consider to convert legacy themes to a community maintained material theme extension, but with some restrictions and technical limitations.

## Topics

Here some points/considerations we have to talk about:

- [ ] First of all need a CONTRIBUTING guideline, the current refer to an old theme version and is now obsolete.
- [x] Old schemes must use their current color palette, no new colors.
- [x] Only workbench related changes (not workbench or other customisations) can be made/fixed in order to support latest vscode releases (if needed) or fix opened issues related to the schemes schemes.
- [x] Community themes are bare-bone vscode json theme without custom commands (release notes, set accent etc)
- [x] We can consider to versioning and publishing legacy themes separately (under the material theme org), and maybe ship them as [`extensionPack`](https://code.visualstudio.com/api/references/extension-manifest) so users will automatically download them when installing the main Material Theme extension. They will see them in the color theme menu searching for material theme, but they are part of a different extension.

### Legacy themes now live as independent community-maintained extension here:
https://github.com/material-theme/vsc-community-material-theme

**Comment by dylmye** [comment]
Is there a reason for disabling issues on the community repo? I don't have any issues to make but I was just wondering. Thanks

**Comment by equinusocio** [comment]
Mmm no, they were closed when we created the repository but now can be enabled again.
