### ISSUE TITLE
command 'materialTheme.setAccent' not found

### ISSUE THREAD

**Issue by Priceincoding** [material-theme/vsc-material-theme#438]
**Describe the bug**
Well, after several tries of reproducing and fixing the bug, it seems it is random (90% percent of the time commands do not work).

**To Reproduce**
1. Do a fresh install of the extension pack OR restart vscode
3. Run any 'materialTheme' command
4. Errors appear

**Expected behavior**
Command should work

**Comment by LasaleFamine** [comment]
Related to #431
