### ISSUE TITLE
[Question] Syntax colors for nodejs

### ISSUE THREAD

**Issue by BannerBomb** [material-theme/vsc-material-theme#439]
Hey, did the syntax color change for nodejs because I have liked the original colors before the update made 19 hours ago. Now everything looks so blue. 
![image](https://user-images.githubusercontent.com/11788894/72208950-208bb200-3477-11ea-9345-d8ff5c964971.png) Like in the image I don't remember the `this` variable being blue. Same for `module.exports`  :thinking:

--- Update ---
By the way I am talking about the Default Material Theme

**Comment by BannerBomb** [comment]
nvm, I found the one I liked is not called `Community Material Theme` :smile: I wish there was a port of this for Visual Studio Community tbh. :heart:

**Comment by equinusocio** [comment]
Community Material Theme is our community-maintained old schemes extension which is downloaded automatically with the official Material Theme. 

About the issue you opened, can you provide a valid snippet and the language extension used?

**Comment by erwinknoop** [comment]
I also experienced some color differences on one of the latest updates when writing React code with Typescript. I was using the Palenight high contrast theme and I switched to the community version now. Was this intentional or did something go wrong? It seems like some of the red and gray colors became inverted.

Colors after update:
![Screenshot 2020-01-13 at 11 44 36](https://user-images.githubusercontent.com/24375678/72249852-910f0c00-35fa-11ea-99cc-7090c53b74ba.png)

Colors before update (and community version):
![Screenshot 2020-01-13 at 11 44 47](https://user-images.githubusercontent.com/24375678/72249884-a5eb9f80-35fa-11ea-809c-1fff9c26321c.png)

**Comment by equinusocio** [comment]
@BannerBomb The `this` should be white/foreground, we'll investigate about it and the `module.exports` scopes

**Comment by equinusocio** [comment]
@BannerBomb can you provide a valid code snippet?

**Comment by BannerBomb** [comment]
this is how it looks on Babel JavaScript.
![image](https://user-images.githubusercontent.com/11788894/72753248-5f65ea00-3b92-11ea-87bd-f638b5909544.png)

If that's what you mean by valid code snippet :thinking:

**Comment by equinusocio** [comment]
Nope 😅 we need a code snippet that doesn't contains errors to copy and paste and inspect inside vscode.

**Comment by BannerBomb** [comment]
```js
module.exports = class MyClass {
	constructor() {
		this.property = true;
	}

	async method() {
		console.log('test');
	}

	static staticMethod() {
		console.log('static');
	}

	get getterMethod() {
		return this.property;
	}

	set setterMethod(arg) {
		this.property = arg;
	}
}
```

I also noticed if you dont add `()` then async, get or set will appear white until you do. But static is highlighted even if you dont use the `()`'s 
![image](https://user-images.githubusercontent.com/11788894/72933477-cec51080-3d2f-11ea-9771-8020d6d495c3.png)
![image](https://user-images.githubusercontent.com/11788894/72933603-0a5fda80-3d30-11ea-95d9-d57590bf1764.png)

**Comment by sunknudsen** [comment]
The colour of the parenthesis and brackets has also changed to red which is "alarming".

See https://stackoverflow.com/questions/60507481/why-have-parenthesis-become-red-in-visual-studio-code-when-writting-typescript?noredirect=1#comment107043369_60507481

**Comment by BannerBomb** [comment]
@equinusocio now everything has turned red after the last VSCode update
![image](https://user-images.githubusercontent.com/11788894/76284155-deae9a80-6272-11ea-91ef-77027a488e2a.png)

**Comment by equinusocio** [comment]
@BannerBomb Community Material Theme are not maintained by us. Ask to become a contributor to do the fix. Anyway, it's not a bug, now vscode assign the correct scope to multiple elements, to revert this fix try adding `"editor.semanticHighlighting.enabled": false`

**Comment by Spittal** [comment]
Hey I'm not OP, but I can confirm the same issues as mentioned above. Setting `editor.semanticHighlighting.enabled` to `false` addresses some of the issues I had, but brackets are still red.

I'm on the official (not community) maintained PaleNight High Contrast theme. Editing a `.js` file.

![material](https://user-images.githubusercontent.com/1229177/76328318-65ca3580-62a8-11ea-91fd-61997b57bce4.gif)
