### ISSUE TITLE
HTML not highlighted

### ISSUE THREAD

**Issue by jonathangraf** [material-theme/vsc-material-theme#441]
HTML files are no longer highlighted by this extension 
**To Reproduce**

1. Set Color Theme to a Material Theme (e.g.: Material Darker)
2. Create/open HTML file 
3. Write HTML code
4. Observe no highlighting on all tags but `<!DOCTYPE html>`

![Bildschirmfoto 2020-01-13 um 09 18 46](https://user-images.githubusercontent.com/39404597/72241249-a0845a00-35e6-11ea-8bf0-7fa0d3c56c62.png)

Will this be available again in the future?

**Comment by equinusocio** [comment]
This issuse seems not related to this theme and we're not able to reproduce it. This is what you should see.

![Screenshot 2020-01-13 at 12 08 11](https://user-images.githubusercontent.com/10454741/72251126-7e4a0680-35fd-11ea-88f0-2dc61358d418.png)

**Comment by vasilenka** [comment]
Just FYI, I am getting this too on VS Code Insiders both on the material theme and community theme, but not on the stable VS Code release.

Syntax highlight works fine when you selecting a color theme, but a few seconds later the color changes into plain white.

**Comment by equinusocio** [comment]
Let's see if the bug will persist on the next stable release.

**Comment by jonathangraf** [comment]
My issue was fixed after disabling another extension. The issue was fixed by the other extension. So in short sorry for jumping to wrong conclusions. @vasilenka try disabling every highlighting related extension to make sure the issue stems from material-theme.
