### ISSUE TITLE
[PHP] class name syntax issue

### ISSUE THREAD

**Issue by Chris1904** [material-theme/vsc-material-theme#444]
Currently using the Material Theme High Contrast it displays as such:

![image](https://user-images.githubusercontent.com/6228425/72301739-9b420200-361c-11ea-9517-7d3ea859450b.png)

The legacy theme treated it like this:
![image](https://user-images.githubusercontent.com/6228425/72301791-c3c9fc00-361c-11ea-8c37-d505370913b1.png)

Not sure if this is a bug or not, but to me the new theme is less readable here. I would expect `OpenMedia` to be colored differently, compared to the leading and following word.

Thanks!

**Comment by thinkstudeo** [comment]
Same issue. As a workaround how to override the class name syntax colour via `editor.tokenColorCustomizations` in  `settings.json`? If anyone can help please

**Comment by equinusocio** [comment]
Hi @Chris1904, can you provide a valid code snippet and name of language extension used?

---

@thinkstudeo, you can add this to your configuration, but you need to fine the correct scope to use with the built-in scope inspector tool:

```json
"editor.tokenColorCustomizations": {
    "[Material Theme VARIANT]": {
        "textMateRules": [
            {
                "scope": [
                    "punctuation.definition.comment"
                ],
                "settings": {
                    "foreground": "#FF0000"
                }
            }
        ]
    },
},
```

**Comment by thinkstudeo** [comment]
Thanks @equinusocio 
I had to add the following
```json

  "editor.tokenColorCustomizations": {
    "[Material Theme Darker]": {
      "textMateRules": [
        {
          "scope": [
            "entity.name.type.class",
            "meta.use",
            "support.class"
          ],
          "settings": {
            "foreground": "#FFCB6B"
          },
        },,
        {
          "scope": [
            "support.class.builtin",
            "entity.other.inherited-class"
          ],
          "settings": {
            "foreground": "#C3E88D"
          },
        }
      ]
    },
  }
```
to get back similar to the legacy theme

**Comment by thinkstudeo** [comment]
> Hi @Chris1904, can you provide a valid code snippet and name of language extension used?
> 

@equinusocio 
Guess it's using Laravel framework and the language extension commonly used is built in `PHP` only - I mean no special language extension specific for Laravel - that's what I use

**Comment by equinusocio** [comment]
@thinkstudeo If you prefer old schemes, consider using Community Material Theme extension!

**Comment by thinkstudeo** [comment]
> @thinkstudeo If you prefer old schemes, consider using Community Material Theme extension!

I'm not averse to new schemes, though I like the old schemes for the reason that various tokens are differently coloured for easy identification - no specific choice of colours.

However in the new scheme the `class` keyword and the class name `OpenMedia` are both having same colour which is not only different compared to old schemes, but the differentiation part is lost I feel.

Will the new schemes drop colour differentiations?

**Comment by equinusocio** [comment]
Nope, new schemes use same colours but applied differently and with consistency, so now eg. variables will have the same colour across languages, but old new schemes will not look the same as the legacy ones.

**Comment by Chris1904** [comment]
Thanks @thinkstudeo, your settings are making it look pretty again :D 

@equinusocio it's just a Laravel install, so this [controller](https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Controller.php) will replicate the issue for you.

**Comment by thinkstudeo** [comment]
> Nope, new schemes use same colours but applied differently and with consistency, so now eg. variables will have the same colour across languages, but old new schemes will not look the same as the legacy ones.

Variables having same colour across languages would be better for mental mapping I guess. 

Don't have specific preferences for any colour, but colour differentiation of tokens is something which I have enjoyed and has made me stick to `vsc-material-theme`. 

Hence I assume that `class` keyword and `OpenMedia` class name will have different colour and currently it's a bug which will get sorted out - is my understanding right?

BTW: Huge thanks for all your efforts in making, maintaining & enhancing this theme.

**Comment by equinusocio** [comment]
Currently the class name is yellow, what we have to fix is the `use App\etc` but I need the snippet to check  scopes

**Comment by thinkstudeo** [comment]
> Thanks @thinkstudeo, your settings are making it look pretty again :D

Glad, could be of help

**Comment by thinkstudeo** [comment]
> Currently the class name is yellow, what we have to fix is the `use App\etc` but I need the snippet to check scopes

When checking with scope inspector tool, I get the following scopes:

Scope for class name: `entity.name.type.class`
Scope for use statements: `meta.use` till the last part i.e. the class (source) name the scope for the source name is `support.class`

**Comment by Chris1904** [comment]
@equinusocio does the snippet I linked to not work? How about this? https://github.com/laravel/laravel/blob/master/app/Http/Controllers/Auth/RegisterController.php

**Comment by equinusocio** [comment]
Yes! I'm working on it, does this suit for you?
<img width="590" alt="Screenshot 2020-01-15 at 19 40 30" src="https://user-images.githubusercontent.com/10454741/72461260-e56ae500-37ce-11ea-85f3-a69dead20a47.png">

**Comment by thinkstudeo** [comment]
This looks pretty good except for the colour for `keyword` **class** and `entity.name.type.class` **Controller** being same. 
Will the colour for `entity.name.type.class` be set to a different colour by the theme or will it be the same  - purple colour as in the image above.

**Comment by equinusocio** [comment]
This is what we can achieve keeping consistency
<img width="544" alt="Screenshot 2020-01-15 at 20 12 29" src="https://user-images.githubusercontent.com/10454741/72463381-688e3a00-37d3-11ea-80b8-d3facdf66e29.png">

**Comment by thinkstudeo** [comment]
Pretty cool. 🙌  👍  👏

**Comment by equinusocio** [comment]
The final result

<img width="565" alt="Screenshot 2020-01-15 at 20 21 36" src="https://user-images.githubusercontent.com/10454741/72463922-a2ac0b80-37d4-11ea-959a-860afb6a54d7.png">

**Comment by thinkstudeo** [comment]
👍 Looks more pleasing to the eye - even better than the earlier. Can't wait for the update 😄

**Comment by equinusocio** [comment]
Released.

**Comment by thinkstudeo** [comment]
Great. Thanks!

**Comment by MrEduar** [comment]
Oh, my God, how awful.
How can I go back to the previous version?

**Comment by equinusocio** [comment]
@MrEduar Just a suggestion, next time avoid such kind of comments on open source projects without:

1. Searching for similar issues
2. Using the correct "tone of voice"
3. Checking the readme/Release notes.
