### ISSUE TITLE
Material Theme Darker High Contrast Comments Coloring

### ISSUE THREAD

**Issue by JCron245** [material-theme/vsc-material-theme#445]
Hopefully this is the appropriate place for this. I really enjoy the Material Theme collection and particularly I like the Darker High Contrast version. However I have had to stop using it as I am unable to actually read comments in this mode.

It appears the background is close to #212121, and comments are getting colored with something close to #4a4a4a which only provides a contrast ratio of 1.82 (Contrast of 4.5 is the bare minimum for passing WCAG - AA standard) which would be impossible for anyone with visual impairments to see (almost impossible for a fully sighted user as well). Not sure if you all would considering lightening the text a little to make them readable?

Picture below for an example!

![Annotation 2020-01-15 113301](https://user-images.githubusercontent.com/1250639/72461061-5e484d80-378b-11ea-9bc6-e06382ac40d8.png)

**Comment by equinusocio** [comment]
Hi JCron, check this readme section about customisations!
https://github.com/material-theme/vsc-material-theme#color-scheme-override

You can add this to your settings:

```js
"editor.tokenColorCustomizations": {
    "[Material Theme Darker High Contrast]": {
        "comments": "#229977"
    }
},
```

**Comment by JCron245** [comment]
Awesome I totally missed that! Thank you so much
