### ISSUE TITLE
Styled Components CSS highlighting broken?

### ISSUE THREAD

**Issue by elramus** [material-theme/vsc-material-theme#446]
**Describe the bug**
After update installed this morning, 32.2 I believe, CSS highlighting inside Styled Components stopped working. 

**To Reproduce**

Install VSCode, install Material Theme
```
npx create-react-app color-test
yarn add styled-components
```
```
const Container = styled('div')`
    margin-top: 1rem; /* Not highlighted properly */
`
```

**Expected behavior**
Correct CSS syntax highlighting. Looks like the rule values are fine but the rules themselves are highlighting the same as nested tags and classes. 

**Screenshots**
Material Theme Ocean:
![Screen Shot 2020-01-16 at 8 41 53 AM](https://user-images.githubusercontent.com/24811404/72534295-2ea54e00-383c-11ea-9110-b801245951f2.png)

For reference, here's Community Material Theme Ocean:
![Screen Shot 2020-01-16 at 8 49 28 AM](https://user-images.githubusercontent.com/24811404/72534891-35809080-383d-11ea-9778-12e0c83d6b29.png)

**Additional context**
Worked perfectly yesterday. Release notes just now said there might be regression probs and to open issues so here I am :) 

Also thanks for the awesome theme, keep up the great work.

**Comment by equinusocio** [comment]
Hi, can you add a screenshot of what you currently see?

**Comment by elramus** [comment]
This is what I'm seeing:

![72534295-2ea54e00-383c-11ea-9110-b801245951f2](https://user-images.githubusercontent.com/24811404/72549517-75a03d00-3856-11ea-8001-022dfa23e2eb.png)

**Comment by equinusocio** [comment]
Should be fixed with 32.3

**Comment by elramus** [comment]
Awesome, thanks @equinusocio for the fast response. Is it expected behavior that pseudo selectors should be colored the same as rule names?

Here's what I'm seeing now in styled components:
![Screen Shot 2020-01-16 at 2 07 42 PM](https://user-images.githubusercontent.com/24811404/72559130-beadbc80-3869-11ea-9416-f81c55400796.png)

But here's what I'm seeing in an SCSS file:
![Screen Shot 2020-01-16 at 2 09 39 PM](https://user-images.githubusercontent.com/24811404/72559212-e69d2000-3869-11ea-9dc3-df0228b61523.png)

**Comment by equinusocio** [comment]
Sorry guys, check 32.4 :/
