### ISSUE TITLE
Color Issues with Fortran

### ISSUE THREAD

**Issue by StephenDiIorio** [material-theme/vsc-material-theme#447]
**Describe the bug**
Since the update to v31 coloring issues with Fortran code (I know dated) are occurring that didn't exist in prior versions. In particular, the coloring of parentheses of 'class' and 'type' keywords aren't respected, every word seems to be identified as something such that they are colored red, and arguments to functions and the commas aren't colored correctly.

**To Reproduce**
Use the latest version and open any piece of Fortran code.

**Expected behavior**
I don't expect every word to be highlighted some color and would like for parentheses to be respected.

**Screenshots**
Before version 31, and using the Community version of Palenight High Contrast, code would look as follows:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/11286278/72562141-b6a94900-3878-11ea-9039-75cf2c453d89.png">

Now, code looks as follows:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/11286278/72562161-c2950b00-3878-11ea-97f4-ed2d669cbd75.png">

**Comment by equinusocio** [comment]
Hi, currently we don't support Fortran language yet, can you share a valid code snippet?

**Comment by StephenDiIorio** [comment]
I thought that was the case, and I have an external language server that handles Fortran code (I don't know if it specifically handles the highlighting of words, however), but it hasn't updated since all of this so I figured something on the theme side has changed to cause these issues.

I imagine when you said a valid code snippet, you want a small piece of code that doesn't necessarily run on its own? This is a complete subroutine on its own that I think has a lot of the issues I bring up.

`subroutine advance_density( this, dt )
!-------------------------------------------------------------------------------

  class(t_neutral), intent(inout) :: this    ! neutral array
  real( p_k_fld ), intent(in) :: dt

  select case ( p_x_dim )
    case (1)
      call advance_density_1d(this, dt)
    case (2)
      call advance_density_2d(this, dt)
    case (3)
      call advance_density_3d(this, dt)
    case default
      ERROR('p_x_dim has the value:', p_x_dim)
      call abort_program(p_err_invalid)
  end select

end subroutine advance_density`

**Comment by equinusocio** [comment]
This should be fixed now
