### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cristianbarreto-bs** [material-theme/vsc-material-theme#449]
- Issue Type: `Performance`
- Extension Name: `vsc-material-theme`
- Extension Version: `32.4.0`
- OS Version: `Linux x64 4.19.96-1-MANJARO`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/kamiloc/Equinusocio.vsc-material-theme-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by equinusocio** [comment]
We are not able to associate this issue with the extension because we have high CPU load even without the extension installed. Can you provide more info?

**Comment by cristianbarreto-bs** [comment]
Sorry i have deleted the file named in the previous comment. I didn't have this problem again, feel free to close this issue.
