### ISSUE TITLE
Pls change extensionKind to ["ui", "workspace"] 

### ISSUE THREAD

**Issue by egamma** [material-theme/vsc-material-theme#452]
This extension has migrated to the `extensionKind` syntax, thanks.

The `extensionKind` is currently set to `["ui']` this means the extension will only run in the desktop extension host. However, based on my testing and reviewing the code, this extension can also run in the remote extension host. For this reason the `extensionKind` should be generalized to `["ui", "workspace"]` (for more details pls see https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location). This will enable that the theme also works when VS Code is run in the browser.

**Comment by equinusocio** [comment]
We had some issues with notifications and settings writing in the past. Can you check if there are no problems with that? Then, a PR is welcome.

**Comment by egamma** [comment]
@equinusocio makes sense I'll do some more checking. 

>settings writing in the past

Do you remember which scenario did not work?

**Comment by equinusocio** [comment]
Never mind, we added `"ui"` after this issue:
https://github.com/material-theme/vsc-material-theme/issues/347

**Comment by egamma** [comment]
@equinusocio 

>Never mind, we added "ui" only after this issue: #347

This is good. What happened is that we have decided to make the `extensionKind` property more expressive and changed the format in 1.41  https://code.visualstudio.com/updates/v1_41#_deprecated-string-type-for-extensionkind. 

For a theme the desired extension kind definition is `"extensionKind": ["ui", "workspace"]`. This means a theme prefers to run on the UI side but it can also run on the remote side.

Your material theme is actually an extension pack an all extensions need to be considered:

- vsc-material-theme the extension pack - this extension pack - it should be changed to `"extensionKind": ["ui", "workspace"]` and from inspecting the code this will work since you are only using VS Code API.
- equinusocio.vsc-community-material-theme - this is the color theme - since the color theme has no code but only theme declarations it can run in the remote extension host. Therefore its extensionKind should also be changed to `"extensionKind": ["ui", "workspace"]`.
- equinusocio.vsc-material-theme-icons - this is the icon theme - this extension has no extensionKind defined and will be inferred to be a "workspace" extension using our heuristics since it has code. However, the current implementation of this extension depends on the layout of the VS Code client installation
https://github.com/material-theme/vsc-material-theme-icons/blob/master/src/lib/persistent-settings.ts#L23. This is done to find the location of a custom settings file. When this extension is run as a workspace extension then this will not work and this explains what you said above:

>We had some issues with notifications and settings writing in the past. 

The good news is that this can easily be fixed, since VS Code provides API to find such a storage location `vscode.globalStoragePath` see https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L5101. If you use this API instead of dependending on the installation location, then the extension can run both as a "ui" and "workspace" extension and its extensionKind can be set to `"extensionKind": ["ui", "workspace"]`.

I can make a PR for this, if you are willing to take it.

**Comment by equinusocio** [comment]
Currently we have just two extension:

- [Material Theme](https://github.com/material-theme/vsc-material-theme)
- [Material Theme Icons](https://github.com/material-theme/vsc-material-theme-icons)

The community version of the theme is not maintained anymore and we deprecated it. and the source code is available only to ones who want to being a contributor of that version.

Anyway, if I understand correctly, we can set `"extensionKind": ["ui", "workspace"]` on the main theme extension, and after the fix, also on the icons extension. Right?

If you can help us with that fix and send a PR we really appreciate it. @LasaleFamine is the man who follow the extensions development and can help you reviewing the PR.

**Comment by egamma** [comment]
> Currently we have only two official extensions

The [Material Theme extension](https://github.com/material-theme/vsc-material-theme) is an extension pack and the pack still refers to the color theme extension and it will be installed with this extension https://github.com/material-theme/vsc-material-theme/blob/88c079e7c2137a09fde677aab54823f72bd767ea/package.json#L27. Is this intentional?

>Anyway, if I understand correctly, we can set "extensionKind": ["ui", "workspace"] on the main theme extension, and after the fix, also on the icons extension. Right?

This is correct.

>If you can help us with that fix and send a PR we really appreciate it. 

will do.

**Comment by egamma** [comment]
@LasaleFamine I've submitted the PR https://github.com/material-theme/vsc-material-theme-icons/pull/144.

**Comment by equinusocio** [comment]
@egamma we've released all the extensions with this change.

**Comment by egamma** [comment]
@equinusocio thank you!
