### ISSUE TITLE
Source Control input box issue on Material Themes.

### ISSUE THREAD

**Issue by gencer** [material-theme/vsc-material-theme#454]
**Describe the bug**
Source Control Input box has no border and when i click inside, it narrows down a bit also selection of the text is almost invisible.

I've attached 2 gifs. Attention to the File search + Replace input boxes. They have solid borders. When i click those borders are still visible. And selection of the text also very visible.

Now look at your Lighter theme. Source Control (Git) Input box has no border and even when you click, it behaves abnormally. Like border (with same color) disappears and the selection of the content nearly invisible.

**To Reproduce**
Just use one of the themes. For me its Lighter.

**Expected behavior**
All input boxes have same look and feel.

**Screenshots**
**This is behavior of Material Themes:**

![2020-02-12_21-51-06](https://user-images.githubusercontent.com/1711576/74366922-fdd81a80-4de1-11ea-8376-dea025b31ca3.gif)

This is the behavior of VSCode Light Theme:
![2020-02-12_21-50-30](https://user-images.githubusercontent.com/1711576/74366945-0cbecd00-4de2-11ea-8fb2-65d6845d85c0.gif)

**Additional context**
Was working up to 1.41.1 of VSCode. Issue arises on 1.42.0. Maybe related to vscode however, it might be causes of recent updates of this theme...

**Comment by equinusocio** [comment]
This is caused by a recent vscode update that apply `focusBorder` style on all inputs too. This key was set to transparent in order to hide focus border on panels elements. Need to find another way.
