### ISSUE TITLE
[Clojure] Many Clojure keywords are not highlighted

### ISSUE THREAD

**Issue by AmitGolden** [material-theme/vsc-material-theme#457]
**Describe the bug**
Many Clojure special forms keywords, like recur, if, let,~, `, ~@, ', fn, loop, keys (:key) and many more, stay white and are not highlighted.

**To Reproduce**
Type any of these keywords inside of parentheses and they will stay white.

**Expected behavior**
Special forms should be cyan-colored and should be in italics, and keywords (names which start 
 with a colon (like :key)) should be colored as well (maybe in red).

**Screenshots**
![Untitled drawing](https://user-images.githubusercontent.com/39828974/75179701-504efa80-5743-11ea-96d2-c9095792f750.png)
Here all the recur, let, if, loop and fn statements should be highlighted.

![Untitled drawing](https://user-images.githubusercontent.com/39828974/75258088-a5941600-57ee-11ea-98ad-c1d0526e5dda.png)
Here all the keywords should be colored.

**Additional context**
This is by far my favorite color theme and I really enjoy using it, thank you for your wonderful work!

**Comment by equinusocio** [comment]
PLease provide a valid code snippet to test

**Comment by AmitGolden** [comment]
```
(defn id-validation-digit
  [id]
  (- 10 (mod
         (reduce (fn [sum digit]
                   (+ sum
                      (let [mul (*
                                 (-> digit last str Integer.)
                                 (+ 1 (mod (first digit) 2)))]
                        (if (> mul 9)
                          (+ (int (/ mul 10)) (mod mul 10))
                          mul))))
                 0
                 (map-indexed vector id))
         10)))
```
Here `let`, `if`, `fn` should be in italics, and cyan colored, like `defn`.

```
(ns learn-clojure.core
  (:require [clojure.string :as str])
  (:require [clojure.spec.alpha :as spec])
  (:gen-class)) 
```
Here all the keywords (names which start
with a colon (like :key)) should be colored.
Thanks!

**Comment by equinusocio** [comment]
Clojur support should be improved next release

**Comment by AmitGolden** [comment]
Thank you!
