### ISSUE TITLE
Syntax highlighting messes up after a few seconds.

### ISSUE THREAD

**Issue by johnRivs** [material-theme/vsc-material-theme#459]
**Describe the bug**
Syntax highlighting messes up after a few seconds. When I visit the file again it's almost instant though.

**To Reproduce**
I open a file, see the normal theme and after a few seconds the theme changes.

**Expected behavior**
Theme stays the same.

**Screenshots**
Before
![](https://i.imgur.com/rUkmCs0.png)

After
![](https://i.imgur.com/8tmJert.png)

**Additional context**
Happens on Javascript and PHP files. Console in developer tools doesn't show anything weird. VSCode version is 1.43.0. Extension version is 32.5.0. Community Material Theme version is 1.4.1 although it doesn't seem to be related since the issue happens when I disable it.

**Comment by equinusocio** [comment]
https://github.com/material-theme/vsc-material-theme/issues/458
