### ISSUE TITLE
Acrylic/Vibrancy effect variant

### ISSUE THREAD

**Issue by jose-a-sa** [material-theme/vsc-material-theme#460]
Would be amazing if you could consider a theme variant with the effect described in this theme:
https://github.com/EYHN/vscode-vibrancy
Unfortunately, this theme/extension only allows the Dark+ theme. It would be amazing to combine the colour schemes from this theme with acrylic effect.

**Comment by equinusocio** [comment]
Hi, we're not interested in such implementation, it requires hacks and extra works that may be changed anytime
