### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by Stanzilla** [material-theme/vsc-material-theme#467]
Heya, for something like I theme I would expect there to be more screenshots of the actual looks on GitHub and on the website (https://material-theme.site/) for someone to know how your theme looks like there is no other way to find out than to install it, which might be intentional? Anyway, a few more screenshots would be great.

**Comment by equinusocio** [comment]
We like test drive :) Installing a theme is not time consuming and can be easily reverted. Anyway, you want to prepare a collection of screenshots we're happy to link it to the README. 👍

**Comment by Stanzilla** [comment]
I mean I don't think that many people will install a theme without knowing how it looks like 😄

**Comment by opensas** [comment]
I absolutely agree with this, I'm not installing any theme without at least having a look at it and see that I liked it... I think that normally you would expect a couple of screenshots when having a look at a theme

**Comment by equinusocio** [comment]
We agree. That's why there is a screenshot inside the readme. We're welcome to accept any PR to add themes screenshots to the README or external link.

**Comment by Stanzilla** [comment]
I don't see a screenshot in Readme.md?

**Comment by samipshah100** [comment]
I dont see a screenshot either

**Comment by equinusocio** [comment]
https://material-theme.site/
