### ISSUE TITLE
[Python] Add different color to function arguments and imported module names other than white

### ISSUE THREAD

**Issue by sys-temd** [material-theme/vsc-material-theme#470]
I understand that you assign white color to variables. But can we have different color for function **arguments** as well as for imported **modules** other than white? Function arguments are lot more used than variables and if you have a **local** function variable then both are given white color which makes local variables and function arguments slightly inseparable from rest of the code when used together (see line 13). Imported module names are also given white color (see line 1-3) and they are extensively used more than variables.

**tl,dr**:
Can we not have white color for function arguments and imported module names to make them look different from variables?

This is not a huge issue. But an improvement would be great as every other theme does this.

**Describe the solution you'd like**
If module name, function arguments and variables have different scope then I recommend to assign module name and function arguments different color from variables to maintain uniqueness of the keywords.

**Additional context**

<img width="960" alt="Annotation" src="https://user-images.githubusercontent.com/56245956/79063505-c1307e80-7cbf-11ea-8dba-1fb67690de7b.png">

**Comment by equinusocio** [comment]
Yes, vscode provides a cool system to custom themes and colors. Check it out:
https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme

**Comment by sys-temd** [comment]
@equinusocio Why not assign those keywords a different color into your theme as a standard? Every other theme does this. Python already has less colors as compared to other language syntax.

**Comment by equinusocio** [comment]
We're currently focused elsewhere, the only and quick solution right now is to customize the scheme as you want.
