### ISSUE TITLE
Enable semantic highlighting in the Material theme

### ISSUE THREAD

**Issue by aeschli** [material-theme/vsc-material-theme#472]
Since 1.43, VSCode themes can take advantage of [semantic highlighting](https://code.visualstudio.com/docs/getstarted/themes#_semantic-highlighting).

Every theme controls whether semantic tokens are enabled. So far, only built-in themes have it enabled and I filed this issue to ask you to opt-in for the Material theme as well.

Adoption is easy and there are new cool styling possibilities.

To turn on semantic highlighting for you theme, all you have to do is put
`"semanticHighlighting": true`
in the theme definition file.

There's a good chance that no further change to the theme is needed (thanks to a default mapping from semantic tokens to TextMate scopes (if not, I'd be interested to know, so I can improve the defaults further)). 

But, more interestingly, themes can tune and go wild by defining new styling rules against the semantic tokens:
```json
"semanticTokenColors": {
    "variable.readonly": "#ff0000", 
    "parameter": { "fontStyle": "underline" },
    "*.declaration:java": { "fontStyle": "bold" }
} 
```

Check out our [Semantic Highlighting Wiki](https://github.com/microsoft/vscode/wiki/Semantic-Highlighting-Overview) and the [Semantic Highlighting Guide](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) for more details and feel free to ping me in this issue if I can help.

Thanks for the great work and looking forward to semantic highlighting in your theme.

**Comment by equinusocio** [comment]
Unfortunately our theme doesn't support such huge and breaking change. By enabling the semanticHighlight most of the tokens lose their color, and some of them use a different color. This would required a huge rewrite :(

You can try it by yourself by enabling it.

**Comment by aeschli** [comment]
There has been quite some fixes since we enabled it the first time for all themes. So the 'loosing all color' bug is now gone.
I just quickly tried and it looks quite good. 
![material](https://user-images.githubusercontent.com/6461412/80122502-f1183580-858d-11ea-8326-a8e7f5d8d2b9.gif)

Thanks for the link, I'll make a request to https://github.com/moxer-theme/code-theme-generator

**Comment by equinusocio** [comment]
If you want to help us with the generator to face this change, i can send you the data to unlock the files. Just send me an email. 👍🏻

**Comment by equinusocio** [comment]
We released 32.6, if you want to check. The semanticHighlight should be on by default now

**Comment by aeschli** [comment]
Awesome, In just wanted to file a request against https://github.com/moxer-theme/code-theme-generator and I see you already fixed it there. Thanks a lot!
Let me know if you run into any issues.

**Comment by equinusocio** [comment]
@aeschli we have some issue here #473
