### ISSUE TITLE
Material Theme Darker, incorrect color of the objects

### ISSUE THREAD

**Issue by arsensaliev** [material-theme/vsc-material-theme#473]
Incorrect color of the objects. This morning it was normal, objects were displayed in red. After 5-6 hours, objects are not highlighted in red. They turned white. Why?
Before: http://joxi.ru/v2985RptznR1Om
After: http://joxi.ru/n2Yo6LxCZKOvMr
How do I solve this problem ?

**Comment by arsensaliev** [comment]
The objects were red.

**Comment by arsensaliev** [comment]
It was red for almost 1 second, and then white again.

**Comment by equinusocio** [comment]
This is related to the recent vscode changes:
https://github.com/material-theme/vsc-material-theme/issues/473

**Comment by bibblebabl** [comment]
Same issue. 

![giphy](https://user-images.githubusercontent.com/9008978/80229817-a5cb5900-8659-11ea-9a08-bceb9e87b5b0.gif)



My extensions list 

code --install-extension angryobject.react-pure-to-class-vscode
code --install-extension blanu.vscode-styled-jsx
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension fknop.vscode-npm
code --install-extension formulahendry.auto-rename-tag
code --install-extension ionutvmi.path-autocomplete
code --install-extension jock.svg
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kenhowardpdx.vscode-gist
code --install-extension lannonbr.vscode-js-annotations
code --install-extension leizongmin.node-module-intellisense
code --install-extension lXSPandora.vscode-styled-components-snippets
code --install-extension mikestead.dotenv
code --install-extension mkxml.vscode-filesize
code --install-extension mohsen1.prettify-json
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension Orta.vscode-jest
code --install-extension pmneo.tsimporter
code --install-extension riazxrazor.html-to-jsx
code --install-extension ritwickdey.create-file-folder
code --install-extension ritwickdey.LiveServer
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension sleistner.vscode-fileutils
code --install-extension srmeyers.git-prefix
code --install-extension tomoki1207.vscode-input-sequence
code --install-extension VisualStudioExptTeam.vscodeintellicode

**Comment by equinusocio** [comment]
Please check ps://github.com/material-theme/vsc-material-theme/issues/472

**Comment by aeschli** [comment]
That's intended.
With semantic highlighting, all properties, regardless if from an an object literal (`{ prop: 1 }`) or from a class `class A { public prop; }` get the same classification and this the same color.

It's the color matching TextMate scope `variable.other.property`.

**Comment by aeschli** [comment]
If you feel strongly that this is a loss of information, please add your vote on https://github.com/aeschli/typescript-vscode-sh-plugin/issues/12
