### ISSUE TITLE
Comment slashes are gray alltimes

### ISSUE THREAD

**Issue by dmetzler1988** [material-theme/vsc-material-theme#477]
**Describe the bug**
I modified the comments (so than it is described in the README and on the issue #173).
But the slashes for comments are alltimes gray.

**To Reproduce**
```
    "editor.tokenColorCustomizations": {
        "[Material Theme Darker High Contrast]": {
            "comments": "#229977",
            "textMateRules": [
                {
                    "scope": [
                        "punctuation.definition.comment",
                        "comment.block",
                        "comment.line",
                        "comment.block.documentation"
                    ],
                    "settings": {
                        "foreground": "#FF0000"
                    }
                }
            ]
        },
    },
```

**Expected behavior**
The slashes should also be colored.

**Screenshots**
![image](https://user-images.githubusercontent.com/8446518/82055225-7a6be500-96c0-11ea-981a-2c882be45eb1.png)

**Comment by dmetzler1988** [comment]
Additional information:  
When i  remove the `workbench.colorTheme` line and the line with the theme declaration, then it works so than it should.

**Comment by equinusocio** [comment]
Replace `punctuation.definition.comment` with `comment punctuation.definition.comment`.

Bonus tip, VSCODE provide a useful tool to inspect syntax scopes and tokens:
<kbd>CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> and search for "Scope"

**Comment by dmetzler1988** [comment]
Ok, that works, thank you a lot!

The tip is very great! Doesn't know this. Thanks a lot!

One additional thing:  
Can you please update the "Advanced example" in README docu for it?
https://github.com/material-theme/vsc-material-theme/blob/master/README.md#color-scheme-override

Thanks a lot.

**Comment by equinusocio** [comment]
Done. The tokens needed to target all the comments are now only two:

```
"comment",
"comment punctuation.definition.comment"
```
