### ISSUE TITLE
Adopt VS Code's 'asWebviewUri' API

### ISSUE THREAD

**Issue by mjbvz** [material-theme/vsc-material-theme#478]
Hi, I maintain VS Code's Webview API

## Issue
Our telemetry suggests that your extension uses webviews and may be loading resources in these webviews using hardcoded `vscode-resource:` URIs. These URIs have some important limitations and don't work properly when VS Code is run in a browser. We are also making changes in the desktop version of VS Code that may cause these URIs to not work properly in future versions of VS Code.

While we are making our best effort to continue support existing webview extensions that use `vscode-resource:` URIs on desktop versions of VS Code, we will not able to fully support all uses cases.

## Fix
To ensure that your extension continues to work in as many environments as possible—including on web and remotely—please:

- Switch to use the [`Webview.asWebviewUri` function](https://github.com/microsoft/vscode/blob/307cb32f306a527a30a5b1756e8bf548c141192c/src/vs/vscode.d.ts#L6703) for loading resources.

- Switch to use the [`Webview.cspSource` property](https://github.com/microsoft/vscode/blob/307cb32f306a527a30a5b1756e8bf548c141192c/src/vs/vscode.d.ts#L6714) in content security policies.

These APIs shipped around 2 years ago so they should be available in all modern versions of VS Code. You can find additional information about the issue here: https://github.com/microsoft/vscode/issues/97962

Let me know if you have any questions about this change

**Comment by LasaleFamine** [comment]
Hi @mjbvz, thank you for reporting this. We will investigate as soon as possible and try to update our Webview with the new standards.

**Comment by LasaleFamine** [comment]
So I'm seeing we have only one reference to `vscode-resource` [here](https://github.com/material-theme/vsc-material-theme/blob/e1121178663f5b89495c9330a92f90d0b26aeb05/src/webviews/Webview.ts#L41).  Is there any `scheme` we can specify here to align with the new API or we need to change our implementation? I can't see the available params on the doc about this `scheme` property.

For the `cspSource` property I think we only need to change our meta within the HTML template of our pages and add the CSP specific meta, am I right?

**Comment by mjbvz** [comment]
I think you'll need to update the implementation. 

In both web and desktop, VS Code now runs each webview in its own unique origin. This means that `asWebviewUri` and `cspSource` produce different results for each webview, so unfortunately you can't use hardcode urls

**Comment by LasaleFamine** [comment]
Hi @mjbvz, sorry for the delay but I was really full of work this month.

I've just opened a PR for removing the `vscode-resource` reference using the `asWebviewUri` API. You can check the change here: https://github.com/material-theme/vsc-material-theme/pull/482/files#diff-cbf01068c2a6d68cd7913fb45baf0552R92

Just tell me if we need to make some other change.
