### ISSUE TITLE
Mind helping me change these texts colors?

### ISSUE THREAD

**Issue by jahirfiquitiva** [material-theme/vsc-material-theme#484]
I find the files names and the comments too hard to read... Also, I checked with [contraste](https://contrasteapp.com/) and they fail :/ ...

Would appreciate if you updated the colors or even just helped me change them for my own use.

Thanks in advance!

<img width="355" alt="Shot 2020-07-13 at 09 04 13@2x" src="https://user-images.githubusercontent.com/10360816/87313819-0c894180-c4e8-11ea-966a-4ddfd344bcf9.png">

<img width="243" alt="Shot 2020-07-13 at 09 03 50@2x" src="https://user-images.githubusercontent.com/10360816/87313824-0eeb9b80-c4e8-11ea-87af-c8b561730a52.png">

**Comment by equinusocio** [comment]
Hello, please search for similar issue before open new one. This is similar to #134 #173 #445 #483

Check how to customize your local material theme based on your taste.
https://github.com/material-theme/vsc-material-theme#override-theme-colors
