### ISSUE TITLE
Accent and syntax colors fail AA contrast test

### ISSUE THREAD

**Issue by lmn8** [material-theme/vsc-material-theme#490]
See https://github.com/material-theme/vsc-community-material-theme/issues/8.

**Comment by equinusocio** [comment]
Hello, this doesn't follow our issues template. Closing it.


Also, VSCode provides a powerful API to fully customize your local Material Theme installation as you wish.
https://github.com/material-theme/vsc-material-theme#color-scheme-override

**Comment by lmn8** [comment]
Uhmm does that mean you wouldn't consider optimising your theme's colors, including syntax colors?
