### ISSUE TITLE
Red colored area in editor on Material Theme 

### ISSUE THREAD

**Issue by andreasgarvik** [material-theme/vsc-material-theme#492]
**Describe the bug**
Areas where there isn't any code has a different red-like color then the rest of the text editor.

**Expected behavior**
Editor to have the same color.

**Screenshots**
![image](https://user-images.githubusercontent.com/31240925/89103895-9d7f7880-d415-11ea-88e8-d7dd84cec68e.png)
![image](https://user-images.githubusercontent.com/31240925/89104011-55ad2100-d416-11ea-95ef-58ce70aab094.png)

**Additional context**
Ubuntu 20.04
VS Code 1.47.3

**Comment by equinusocio** [comment]
This looks like a VScode rendering bug.
