### ISSUE TITLE
Embed CHANGELOG.md into the extension

### ISSUE THREAD

**Issue by lostintangent** [material-theme/vsc-material-theme#493]
Hey! First off, thanks for the awesome theme 👋 In order to keep up with changes, I was thinking it would be awesome if the change log could be embedded as a `CHANGELOG.md` file in the extension itself, so that it would naturally show up in the extension details page in VS Code _(like below)_. Currently, I think (?) the change log is only discoverable from the toast that is displayed when the extension is installed/updated, and it would be great to have a predictable entry point for checking out the change log at any time. Thanks!

![image](https://user-images.githubusercontent.com/116461/89108759-f0ded000-d3ef-11ea-9f25-9ed94f6cb63a.png)

**Comment by equinusocio** [comment]
Hello, Material Theme provides a custom command to show the release notes every time you want. Open the command palette and search for `release notes`, then you will see the `Material Theme: Release Notes` command.

**Comment by equinusocio** [comment]
Hi @lostintangent the release notes command is now working again.
