### ISSUE TITLE
Release notes command bug

### ISSUE THREAD

**Issue by equinusocio** [material-theme/vsc-material-theme#495]
**Describe the bug**
The custom Release Notes command isn't working. The page keeps loading.

**To Reproduce**
1. Open command palette
2. Run material theme release notes command

**Expected behavior**
Release notes should load

**Screenshots**

<img width="1378" alt="Screenshot 2020-08-03 at 09 46 04" src="https://user-images.githubusercontent.com/10454741/89158287-290c1d00-d56e-11ea-84cf-8faad0ed797b.png">

**Comment by LasaleFamine** [comment]
This is now fixed, the problem were the CORS on Sanity side.
