### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by ljbrits** [material-theme/vsc-material-theme#496]
I just reinstalled my computer when Ubuntu 20.04, so after reinstalling vscodium I tried to set the theme toe Material and got the error:  Unable to load file:///home/blah/.vscode-oss/extensions/equinusocio.vsc-material-theme-32.8.0/build/themes/Material-Theme-Ocean.json: Unable to read file '/home/blah/.vscode-oss/extensions/equinusocio.vsc-material-theme-32.8.0/build/themes/Material-Theme-Ocean.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/blah/.vscode-oss/extensions/equinusocio.vsc-material-theme-32.8.0/build/themes/Material-Theme-Ocean.json')

Why is vscodium looking for a 'build' directory which is not in source code?

The theme worked fine under 18.04 and vscodium.
Thanks for your help

**Comment by equinusocio** [comment]
This extension must be built. The build directory is created during the extension packaging and before the publish on the market. Since the build step is required, this extension can't be directly used from the git source, you have to install all the dependencies and build it yourself.

**Comment by hackel** [comment]
@equinusocio VSCodium isn't a "3rd party editor based on vscode," it is built directly from the unmodified source repo, making it the *closest* you can get to an official build.  It's even more so than Microsoft's proprietary build which adds extra tracking junk that isn't in the git repo, just as Chromium is even more official than Google's propreitary Chrome build.  Bottom line, there is no reason not to support it, unlike other 3rd party editors that may have modified the code.

You would be most welcome to [take ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access) of [your extension](https://open-vsx.org/extension/Equinusocio/vsc-material-theme) in the Open VSX extension registry and integrate it into your build process.  This registry is not controlled by Microsoft with their invasive license terms.

Also, your README makes no mention of the build process, it just says to clone it and apply the theme straight away.  It would be nice if you explained there exactly what is necessary to get the extension running from source.

Thanks for your work on this project!
