### ISSUE TITLE
Frontmatter inside njk (nunjucks) is formatted as gray comment color

### ISSUE THREAD

**Issue by surjithctly** [material-theme/vsc-material-theme#497]
**Describe the bug**
Frontmatter inside njk (nunjucks) is formatted as gray comment color.

**To Reproduce**
1. Create an .njk file
2. Create a fontmatter using `---`
3. See error

**Expected behavior**
It works fine on markdown
![image](https://user-images.githubusercontent.com/1884712/90778714-982d9380-e31a-11ea-9775-d793bd8d4904.png)

**Screenshots**
but not on .njk file
![image](https://user-images.githubusercontent.com/1884712/90778536-5ef52380-e31a-11ea-99b5-408c4bf1a941.png)

How do I fix? Sorry if this issue is not related to this theme. If so, Can you guide me to the correct place?

**Comment by equinusocio** [comment]
This is an issue related to the nunjucks language highlights. As you can see, the MD language extension assign the correct (YAML) tokens to the front-matter elements:

![Screenshot 2020-08-30 at 10 42 58](https://user-images.githubusercontent.com/10454741/91654996-bda26600-eaad-11ea-88a5-79037cc9b756.png)

While the nunjucks language extension doesn't assign any specific token, so vscode uses the text color fallback:
![Screenshot 2020-08-30 at 10 43 11](https://user-images.githubusercontent.com/10454741/91655008-df035200-eaad-11ea-83ca-b83796c7c2d7.png)

I'm sorry but we can't do anything to fix this. If we apply a color to the `text.html.nunjucks` tokens, every plain text element inside nunjucks files will use this color. You should reach the extension author and ask to support this feature.
