### ISSUE TITLE
Lost Highlight Color on Console

### ISSUE THREAD

**Issue by aaroncrawford** [material-theme/vsc-material-theme#498]
After a recent update, we've lost coloring on the console.log in Javascript.  I'm not sure whether this was after the latest VSCode update, or if maybe the theme itself updated.

I'm personally using Ocean High Contrast, but the coloring disappeared on other variations in Material theme.  See screenshot below.  Before the update, console used to be colored yellow.  Is there any setting that will allow us to get this colored again?
Thanks!
![Screen Shot 2020-08-20 at 3 12 18 PM](https://user-images.githubusercontent.com/3203500/90820779-8be40f00-e2f7-11ea-96a6-281004bbe90d.jpg)

**Comment by equinusocio** [comment]
Can you provide the current vscode version you're using and the previous one? Are you updating vscode frequently?

**Comment by aaroncrawford** [comment]
Sure thing, I'm currently on Version: 1.48.2.

I don't know precisely which version I was on before, but I'm constantly updated, so I'm guessing it was the June/July release.  Thanks!
