### ISSUE TITLE
Porting Material Theme to GitHub 

### ISSUE THREAD

**Issue by CharlieEtienne** [material-theme/vsc-material-theme#506]
Hi,

I would like to propose [my porting of Material Theme for GitHub](https://github.com/CharlieEtienne/material-github).

![2020-11-11_21h35_29](https://user-images.githubusercontent.com/9772943/98863538-cc6fa680-2468-11eb-880e-d7f5a53c168b.png)

Available in Oceanic, Darker, Palenight, or custom.

And as a Palenight addict, I would like to thank you for this awesome theme you created.

**Comment by equinusocio** [comment]
Hello @CharlieEtienne, we'll add this to the README. Thank you for the awesome job 👍
