### ISSUE TITLE
Unable to read file of the Any Theme

### ISSUE THREAD

**Issue by supermavster** [material-theme/vsc-material-theme#507]
**Describe the bug**
When I install the extension of the marketplace (VSCode) and select any theme the next error is displayed and the extension is very useful for me :c Please help me. The error is the next:

**To Reproduce**
1. Go to the extension in the marketplace
2. Click on Set Color Theme
3. Scroll down the themes and click in any theme

**Additional context**
```md
Unable to load file:///home/mavster/.vscode-oss/extensions/equinusocio.vsc-material-theme-33.0.0/build/themes/Material-Theme-Palenight-High-Contrast.json: Unable to read file '/home/mavster/.vscode-oss/extensions/equinusocio.vsc-material-theme-33.0.0/build/themes/Material-Theme-Palenight-High-Contrast.json' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/home/mavster/.vscode-oss/extensions/equinusocio.vsc-material-theme-33.0.0/build/themes/Material-Theme-Palenight-High-Contrast.json')
```

**Note** I use Arch Linux with Code.

Thanks for you time @material-theme

**Comment by LasaleFamine** [comment]
Hi @supermavster, thanks for reporting the issue.

Can you check if the file actually exist in here `/home/mavster/.vscode-oss/extensions/equinusocio.vsc-material-theme-33.0.0/build/themes/Material-Theme-Palenight-High-Contrast.json`? The error is pretty strange, seems like you have a broken installation of the theme.

**Comment by equinusocio** [comment]
This may be related to https://github.com/material-theme/vsc-material-theme/issues/496

Material Theme needs to be built (we do it before every release), if VSCODIUM takes the source from GitHub directly, the build folder is not present.

**Comment by supermavster** [comment]
Exactly @equinusocio, the folder not exist in my PC. only: `/home/mavster/.vscode-oss/extensions/equinusocio.vsc-material-theme-33.0.0`

**Comment by StevenDoesStuffs** [comment]
I am having the same issue, and it is indeed the same issue as #496, as the arch linux package for vscode defaults to the open vsx registry. I understand if the open vsx registry isn't supported officially, but it'd be great if you could add somebody else to maintain the package there.

**Comment by equinusocio** [comment]
@StevenDoesStuffs Is this fixed now? I see the PR has been merged.

**Comment by StevenDoesStuffs** [comment]
Yes

**Comment by equinusocio** [comment]
Thank you! I'm going to close this then.
