### ISSUE TITLE
Material Theme: there was an error while loading the configuration

### ISSUE THREAD

**Issue by Th0rgal** [material-theme/vsc-material-theme#513]
Hello there,

I am using the operating system nixos. It allows me to manage all my software configurations from the same global nix configuration (and thus to port my entire environement to another computer easily).
It works fine with vscode, however I have a little problem. with this theme:
![2021-01-27-001642_494x342_escrotum](https://user-images.githubusercontent.com/41830259/105918867-f7fc3900-6034-11eb-8ce3-7c947d09f2fc.png)

Do you think I could disable the config feature?

Thomas!

**Comment by equinusocio** [comment]
Hello, your FS is read-only as I can see.  I don't think it would be possible because disabling the configuration would require saving that setting somewhere in your config file, it's a kind of paradox.

**Comment by Th0rgal** [comment]
> Hello, your FS is read-only as I can see. I don't think it would be possible because disabling the configuration would require saving that setting somewhere in your config file, it's a kind of paradox.

I can generate it from my nixfiles though.

**Comment by LasaleFamine** [comment]
Hi @Th0rgal I think we need to understand better how to make this work on Nixos (which actually I don't know) and the limitations that come with this. 
Feel free to let us know if you think there is a suitable solution and how to achieve that (or maybe also PR's are welcome!).

Thanks!
