### ISSUE TITLE
is there support for semanticHighlighting ?

### ISSUE THREAD

**Issue by arsensaliev** [material-theme/vsc-material-theme#515]
![image](https://user-images.githubusercontent.com/52528182/107467046-58d85500-6b8f-11eb-92d1-d67dc47f6794.png)

object "b" should be red ? I read the material theme updates and it was written there that semanticHighlighting is supported, but it doesn't work for me(

Semantic Highlighting is disabled here

![image](https://user-images.githubusercontent.com/52528182/107467154-9ccb5a00-6b8f-11eb-8b0b-2fbb9249bbdc.png)

How can I fix this ?

**Comment by equinusocio** [comment]
Hello, what you see is the correct and expected behaviour. Check with the built-in Dark theme,  and share the screen, you shoulìd get the same results, with `b` colored the same way as other variables (`const a`).

**Comment by arsensaliev** [comment]
you're right

**Comment by arsensaliev** [comment]
![image](https://user-images.githubusercontent.com/52528182/108380499-179c1100-7231-11eb-8ce3-fce04a1cf58f.png)
Here the variable a is lighter than the key and and the value is a different color

**Comment by equinusocio** [comment]
Your latest screenshot is different from this:

https://user-images.githubusercontent.com/52528182/107467046-58d85500-6b8f-11eb-92d1-d67dc47f6794.png

**Comment by arsensaliev** [comment]
> Your latest screenshot is different from this one. `a` and `b` use different colors.
> 
> ![](https://user-images.githubusercontent.com/52528182/107467046-58d85500-6b8f-11eb-92d1-d67dc47f6794.png)

because I didn't call the "a" variable"

**Comment by enkeyz** [comment]
Use the Community Material Theme instead. It supports semantic highlighting.

**Comment by equinusocio** [comment]
> Use the Community Material Theme instead. It supports semantic highlighting.

Nope, it doesn't. It just uses the older color scheme.
