### ISSUE TITLE
Porting for Fluent Terminal

### ISSUE THREAD

**Issue by idokaraderu** [material-theme/vsc-material-theme#516]
Hello,

I've created a port of Material Theme to be used in [Fluent Terminal](https://github.com/felixse/FluentTerminal).
https://github.com/idokaraderu/fluent-material-theme

Would it be possible to add it to the Offical Portings in the README?
Thanks!

**Comment by equinusocio** [comment]
Hello, you did an mazing work! Since you added all the variants, yes we agree and this should be listed in the official portings list. If you want you can do it your self by sending a PR with the change on the README (add it after the last item.)

**Comment by idokaraderu** [comment]
Thank you for allowing me to add this to the README!
I will send PR.
