### ISSUE TITLE
Focussed menu item background is no longer controlled by the theme

### ISSUE THREAD

**Issue by pingshunhuangalex** [material-theme/vsc-material-theme#518]
**Describe the bug**
Focussed menu item background is no longer controlled by the theme due to the change of the theme reference key for command menu.

**To Reproduce**
1. Make sure material theme is toggled
2. Open the command menu
3. The background of the selected menu item now always uses a navy blue colour. 

**Expected behavior**
Previously, it was light grey for a darker high contrast setup

**Screenshots**
![image](https://user-images.githubusercontent.com/17170199/108513422-b3537d00-7316-11eb-9088-e994f26f80c3.png)

**Additional context**
The issue is caused by replacing `list.focusBackground`  with `quickInput.list.focusBackground` after VS Code version >= 1.54.

Making corresponding changes in generator files like this (https://github.com/material-theme/vsc-material-theme/blob/master/scripts/generator/settings/specific/darker-hc.ts) should fix it.

**Comment by equinusocio** [comment]
Hello, can you share a link about these changes? In order to check whatelse has been changed.

**Comment by pingshunhuangalex** [comment]
Code change is here: https://github.com/microsoft/vscode/commit/4a941b1853a7b9e0173fd3f9c6eeeb6af13503f0
With proposal here: https://github.com/microsoft/vscode/issues/115873
Thanks.
