### ISSUE TITLE
Material Theme is not on marketplace anymore

### ISSUE THREAD

**Issue by leandrocodes** [material-theme/vsc-material-theme#521]
## EDIT BY MAINTAINERS:

Hi everyone, we are incredibly sorry for what happened, but because of a problem during the publish of a new version and a human error we mistakenly deleted our publisher account on the VSCode marketplace. This followed the deletion of all our public extensions. Seems like a joke after what happened to OVH datacenter, but we are deeply sorry for this.

We immediately sent an email to the VSCode marketplace, but we are waiting an answer before taking an action. 
We will going to update the issue during this time.

If someone of the VSCode team is going to read this and can help us it would be really appreciated.

Thank you for your comprehension 😕

In the meantime, you can get the latest packaged extension here and install it. 😔

## Download

[vsc-material-theme-33.2.0.vsix.zip](https://github.com/material-theme/vsc-material-theme/files/6128187/vsc-material-theme-33.2.0.vsix.zip)

## How to install

https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by fmmendes** [comment]
I'm with the same problem, anyone knows what's happening?

**Comment by LasaleFamine** [comment]
Hi everyone, we are incredibly sorry for what happened, but because of a problem during the publish of a new version and a human error we mistakenly deleted our publisher account on the VSCode marketplace. This followed the deletion of all our public extensions. Seems like a joke after what happened to OVH datacenter, but we are deeply sorry for this.

We immediately sent an email to the VSCode marketplace, but we are waiting an answer before taking an action. 
We will going to update the issue during this time.

If someone of the VSCode team is going to read this and can help us it would be really appreciated.

Thank you for your comprehension 😕

**Comment by equinusocio** [comment]
In the meantime, you can get the packed extension here and install it:

## Download

[vsc-material-theme-33.2.0.vsix.zip](https://github.com/material-theme/vsc-material-theme/files/6128187/vsc-material-theme-33.2.0.vsix.zip)

## How to install it

https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by equinusocio** [comment]
## IMPORTANT ⚠️
Hello everyone, we managed to restore the publisher account but unfortunately all the extensions lose their stats and reviews.  We would appreciate if you all can spend some word and review both Material Theme and Material Theme Icons (we released the v2 right now with the new cons) extensions again. ♥️ 

Another note, we recommend to update both extension to re-sync your local versions with the new ones pushed to the marketplace.

**Comment by leandrocodes** [comment]
Thank you so much!

**Comment by enkeyz** [comment]
Community Themes by Microsoft was also deleted. It contained their own version of Material theme with semantic highlighting.

**Comment by equinusocio** [comment]
`Community Themes by Microsoft` ?

**Comment by equinusocio** [comment]
> Community Themes by Microsoft was also deleted. It contained their own version of Material theme with semantic highlighting.

Community Themes by Microsoft ?

**Comment by enkeyz** [comment]
Community Material Theme: https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-community-material-theme

**Comment by equinusocio** [comment]
Pushed. FYI Community Material Theme is not "by Microsoft" and it's the old community-maintained version of this theme.
