### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by arkapratimsarkar** [material-theme/vsc-material-theme#522]
I installed the theme using the vsix file and got an warning saying - `(node:11421) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

is the theme unsafe to use ?
![buffer warning](https://user-images.githubusercontent.com/75578780/111015920-0f1e9c80-83d1-11eb-8892-a4e297489b4c.png)

**Comment by Ofsen** [comment]
same ! the theme seem to work just fine but the command '🎨 Material Theme: Set accent color' results in an error (command 'materialTheme.setAccent' not found) like so:

![Screenshot from 2021-03-13 20-03-02](https://user-images.githubusercontent.com/24249806/111041174-53dd1e80-8437-11eb-97be-1226373d3db2.png)

**Comment by equinusocio** [comment]
@LasaleFamine

**Comment by LasaleFamine** [comment]
Hi, the buffer deprecation warning is not directly related to our code but to one of our dependency. Anyway this is something that would be fixed asap, but nothing to worry about.

@Ofsen are you sure you installed the theme correctly? Unfortunately I'm not aware of what happens when the extension is installed manually, but the command should be registered when you open VSCode with the theme activated.

**Comment by Ofsen** [comment]
> @Ofsen are you sure you installed the theme correctly? Unfortunately I'm not aware of what happens when the extension is installed manually, but the command should be registered when you open VSCode with the theme activated.

Oh ! you're right ! am on debian, and unziping the zip file creates a folder with the same name "vsc-material-theme-33.2.0.vsix", when i tried to install it in vscode it took this folder as the actual ".vsix" package which was inside the forlder

![Screenshot from 2021-03-14 10-45-37](https://user-images.githubusercontent.com/24249806/111064104-824c0f80-84b2-11eb-9d19-c4de8e20d22d.png)
to the right the ".vsix" package and the `folder` it creates after extracting.
to the left, the actual ".vsix" package

Thank you !
