### ISSUE TITLE
Has this theme heve a misleading name that refers to this project?

### ISSUE THREAD

**Issue by thedonator** [material-theme/vsc-material-theme#523]
Repo link https://github.com/whizkydee/vscode-palenight-theme
Keep up guys love your theme 😄

**Comment by equinusocio** [comment]
Hello, we asked the author to remove that extension or [change its name](https://github.com/whizkydee/vscode-palenight-theme/issues/10), without success. It's just one of the many clones about there. Hope people understand and recognize original works.
