### ISSUE TITLE
RStudio port

### ISSUE THREAD

**Issue by lusignan** [material-theme/vsc-material-theme#524]
Hi, I've added all of the variants of your theme to my [RStudio port](https://github.com/lusignan/RStudio-Material-Theme) and wanted to make sure I was properly acknowledging you on the readme. I love your theme for VSCode and wanted to help bring it to those who primarily use R.

**Comment by equinusocio** [comment]
Hello! Nice work! Feel free to send a PR. Add it at the end of the list, following the same format.
