### ISSUE TITLE
Theme is Not available through the marketplace on VS Code

### ISSUE THREAD

**Issue by ChristosBouronikos** [material-theme/vsc-material-theme#525]
**Describe the bug**
Material theme doesn't show up in the extensions list in VS Code.

**To Reproduce**
1. Go to 'VS Code'
2. Click on 'Extensions' 
3. Search for on 'Material', or 'Theme' and sort by installs 
4. 'Material Theme' **does NOT** show up.

**Expected behavior**
Material theme should show up in the extensions list in VS Code.

**Screenshots**
![Screenshot](https://i.imgur.com/epeyTHo.png)

**Additional context**

**Comment by equinusocio** [comment]
Hello. We had an issue with our publisher account. Check https://github.com/material-theme/vsc-material-theme/issues/521. TL;DR Remove it and reinstall it again.
