### ISSUE TITLE
Question: Palenight Highcontrast methods and properties colors

### ISSUE THREAD

**Issue by alexbeletsky** [material-theme/vsc-material-theme#528]
I've been using Material Palenight for years already and got used to that properties color are grey and the methods color are blue. But recently, I've noticed that the colors have been changed to red,

<img width="500" alt="Screenshot 2021-04-04 at 16 34 01" src="https://user-images.githubusercontent.com/304929/113512221-e028c000-9563-11eb-863e-78f0caa41a43.png">

Here, we have methods `start()`, `stop()` or property `json: true` they are all red color, but used to be blue and grey correspondently.

I'm wondering if this is by design and just changed with a recent update of VS Code of Theme itself, or it's something corrupted in my settings?

Really want to get old colors back, any clues are very welcome :)

**Comment by alexbeletsky** [comment]
Just for the record, I also have 'Communtity Material Theme' installed, this is how it looks,

<img width="500" alt="Screenshot 2021-04-04 at 16 49 21" src="https://user-images.githubusercontent.com/304929/113512642-d2743a00-9565-11eb-8de4-cc28d24b7b16.png">

As you can see, methods and properties are rendered correctly (exactly how it used to be), but it has some other color changes that I don't like.

**Comment by equinusocio** [comment]
Hello, we have not changed the syntax colors since months, but please note that the official Material Theme does support vscode semantic highlight (the new smart way to provide more precise highlight), while the community version of the theme doesn't. So the code from the screenshot you like  is wrongly highlighted.

**Comment by alexbeletsky** [comment]
@alexbeletsky The Semantic Highlighting was exactly the issue! Changed it to "configuredByThere" and everything back to place.

Appreciate your help and appreciate your work! Have a great day :)
