### ISSUE TITLE
Request: Add options to change sidebar items height

### ISSUE THREAD

**Issue by jahirfiquitiva** [material-theme/vsc-material-theme#529]
**Is your feature request related to a problem? Please describe.**
Sidebar items height is too small and I tend to incorrectly click on the wrong items

**Describe the solution you'd like**
Options to set a custom height for sidebar items

**Additional context**
Here's a screenshot of the items I'm talking about:
<img width="165" alt="Shot 2021-04-06 at 16-46-09@2x" src="https://user-images.githubusercontent.com/10360816/113785006-ee114900-96fb-11eb-8098-8442d370ee59.png">

**Comment by equinusocio** [comment]
Hello, there are not API for that. You should open the issue to the Vscode team to discuss this new feature.
