### ISSUE TITLE
Request: Change text color for ignored files

### ISSUE THREAD

**Issue by jahirfiquitiva** [material-theme/vsc-material-theme#530]
**Is your feature request related to a problem? Please describe.**
Text color for ignored files is too dark and really hard to read.

**Describe the solution you'd like**
Use a lighter color for ignored files

**Comment by equinusocio** [comment]
Hello, you can do any change based on your personal taste by using the vscode persistent settings.

```js
"workbench.colorCustomizations": {
	"[Material Theme VARIANT]": {
		"gitDecoration.ignoredResourceForeground": "#ff0000"
	},
}
```

More info here:
https://github.com/material-theme/vsc-material-theme#override-theme-colors

**Comment by jahirfiquitiva** [comment]
@equinusocio thanks for the help 😀

Is there a way to make these files appear with a stroke ~like this~ ?

**Comment by equinusocio** [comment]
> @equinusocio thanks for the help 😀
> 
> Is there a way to make these files appear with a stroke ~like this~ ?

Nope, there are not API to do that.
