### ISSUE TITLE
Accent color selection doesn't work after switching to Ocean High Contrast

### ISSUE THREAD

**Issue by peterrus** [material-theme/vsc-material-theme#534]
**Describe the bug**
While running VSCodium 1.55.2 on  Ubuntu 20.04.

**To Reproduce**
1. Select Darker High Contrast Theme with `ctrl+p`
2. Customize the accent color to anything but the default (I choose orange)
3. Select Ocean High Contrast theme with `ctrl+p`
4. See that the accent color is reverted to the default
5. See that the accent color menu is not shown when selecting 'Set accent color' from either the `ctrl+p` menu or VSCodium's settings.

I have not tested this with VSCode because it is not FOSS, but technically there shouldn't be any differences. Maybe someone can test if they are experiencing the same behavior?

**Expected behavior**
Expected the accent color to stay the same or at least that I would be able to change it after switching the theme. Switching back to the Darker High Contrast theme still renders the accent selection unusable.

**Workaround**
Fully uninstall the theme, restart VSCodium and reinstall the theme. Thereby making sure you don't select the Ocean High Contrast theme.

**Comment by peterrus** [comment]
Did some more tests:

On VSCode (not Codium) v1.55.2 I observe the same behavior, both with the regular theme as with the community maintained version.

Manually setting the accent colors in `settings.json` does work. This way I can set the accent colors for (for example) the Ocean High Contrast theme.

Extension host logs don't seem to show anything but some reason I once got an error popup:

>Command '🎨 Material Theme: Set accent color' resulted in an error (command 'materialTheme.setAccent' not found)

I was unable to replicate that pop up however.

**Comment by equinusocio** [comment]
Can you check if you have the `build` folder inside the extension directory?
