### ISSUE TITLE
Port to Atom

### ISSUE THREAD

**Issue by dragonBall561** [material-theme/vsc-material-theme#540]
**Is your feature request related to a problem? Please describe.**
I like Atom. I also like this theme. But this theme is not for Atom.

**Describe the solution you'd like**
I want this theme ported to Atom

**Describe alternatives you've considered**
I haven't tried any yet

**Comment by equinusocio** [comment]
At the moment we have no plans to do a porting for Atom. If you want a similar experience on that editor, you can try https://github.com/atom-material/atom-material-ui, but it's based on the old material theme.
