### ISSUE TITLE
Why there are different styles for backslash?

### ISSUE THREAD

**Issue by xiajunwen1007** [material-theme/vsc-material-theme#541]
Love this theme so much. Recently, I encounter a problem, that is, there are different styles for backslash? For example
![image](https://user-images.githubusercontent.com/49160447/119284486-68793680-bc72-11eb-8db4-f6bb3415d8d6.png)
Maybe it is a feature, but I wanna have a uniform style. How can I change this? Thank you so much.

**Comment by equinusocio** [comment]
`usePackage` is italic...

**Comment by xiajunwen1007** [comment]
Oh, got it. Other themes like Solarized light can make these backslash be the same style.
![image](https://user-images.githubusercontent.com/49160447/119324489-79e23300-bcb2-11eb-9d29-06baaf9c6207.png)
What can I do if I wanna make them look uniformly? Thank you so much.
