### ISSUE TITLE
Sash (Panel Resize Indicator) not visible when resizing a panel or view

### ISSUE THREAD

**Issue by stagefright5** [material-theme/vsc-material-theme#545]
**Describe the bug**

VSCode has a divider line (sash) that gets shown when resizing a pane or view (Sidebar, Terminal etc)

https://user-images.githubusercontent.com/15051871/123717663-ea283980-d89a-11eb-895c-8964cebcdab0.mp4

This is missing in any of the Material Themes

https://user-images.githubusercontent.com/15051871/123717890-66228180-d89b-11eb-83ba-b289fa6fd05a.mp4

**To Reproduce**
1. Resize terminal or sidebar pane

**Expected behavior**
Sash should be visible

**Screenshots**
Sash is not visible

**Comment by equinusocio** [comment]
Hello, that's not a bug but one of the Material Theme UX features that provides full immersion and distractions free UI. If you want to see dividers, use the "high contrast" variants.
