### ISSUE TITLE
Command '🎨 Material Theme: Set accent color' resulted in an error

### ISSUE THREAD

**Issue by seattleowl** [material-theme/vsc-material-theme#546]
**Describe the bug**
In the readme it says to use the Material Theme: Set accent color to change the accent color, but in use I get a popup saying "Command '🎨 Material Theme: Set accent color' resulted in an error (command 'materialTheme.setAccent' not found)"

**To Reproduce**
1. Open 'Show All Commands' (ctrl/cmd+shift+p)
2. Click on '🎨 Material Theme: Set accent color'
3. See error

**Expected behavior**
Something to show up allowing me to change the accent color.

**Screenshots**
![Screen Shot 2021-07-12 at 6 48 24 AM](https://user-images.githubusercontent.com/32573897/125298629-2cab3680-e2dd-11eb-95e1-05155a922253.png)
![Screen Shot 2021-07-12 at 6 48 17 AM](https://user-images.githubusercontent.com/32573897/125298689-3b91e900-e2dd-11eb-8396-3203877990c7.png)

**Additional context**
I'm on MacOS Big Sur with the latest VSC version.

**Comment by indranildeveloper** [comment]
Yes, I am on a windows machine, but theme accent color is not changing for me as well.

**Comment by cdaringe** [comment]
The supporting fn [seems to be present](https://github.com/material-theme/vsc-material-theme/blob/d8e1accd08a55948174410a470e1f1fc9889d6f6/src/material.theme.config.ts#L22) and command registered 🤔 something perhaps w/ the build is borked? observing it on osx as well

**Comment by equinusocio** [comment]
Please check in the local extension folder if the `build` folder exists.
