### ISSUE TITLE
Keyword colors are all going to light blue

### ISSUE THREAD

**Issue by varunbhalerao56** [material-theme/vsc-material-theme#551]
I really love this theme but recently all the keywords which were originally a purpleish color are turning into this light blue. I am not sure why this is happening but when I use the inspect tool this is what shows up

![image](https://user-images.githubusercontent.com/59999892/126108029-eb6430dd-ae5d-4022-9f33-8f09bf31261e.png)

Is this a change that going forward or its an issue on my side?

When I open vs code the colors are as they were, but after everything loads the colors go the light blue. (3rd image)
![image](https://user-images.githubusercontent.com/59999892/126108203-1dc84b05-9cc4-447e-a373-e38e3b754bee.png)

This is how it looks later
![image](https://user-images.githubusercontent.com/59999892/126107858-af0c81af-b21f-4365-a37d-e187ead5cf4c.png)

**Comment by equinusocio** [comment]
We didn't release any update so probably it the dart extension which now support semantic highlight

**Comment by varunbhalerao56** [comment]
@equinusocio So is there anything I can do about it? If not I can go ahead and close this issue, also thanks for the quick reply.

**Comment by equinusocio** [comment]
@varunbhalerao56 You can check here to disable semantic highlighting for languages:
https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#enablement-of-semantic-highlighting

**Comment by varunbhalerao56** [comment]
Omg! @equinusocio it worked, thanks to a lot man, you made my day I love the original colors!

**Comment by jayypee** [comment]
@varunbhalerao56 can you share your steps please?

**Comment by varunbhalerao56** [comment]
@jayypee Here are the steps I followed:
- Go to VSCode settings
- Search for `editor.semanticHighlighting.enabled`
- Set to false.
