### ISSUE TITLE
Theme suddenly deactivated when Workspace Trust dialog open

### ISSUE THREAD

**Issue by vinnlee** [material-theme/vsc-material-theme#556]
**To Reproduce**
1. Select a project folder/workspace.
2. Right click and choose Open with Code.
3. Workspace Trust dialog is showed.
4. The theme is deactivated.
5. Choose Yes or No and the theme is activated again.

**Expected behavior**
The theme is stayed as it when the Workspace Trust dialog is showed

**Screenshots**

![demo](https://user-images.githubusercontent.com/20036316/148734948-ba969716-c6dc-4bb2-abe0-cbe3bae1aa25.gif)

**Comment by equinusocio** [comment]
We added a verified domain, hope is enough. If not we have not @LasaleFamine we have to update the package json by adding this:
https://code.visualstudio.com/api/extension-guides/workspace-trust#static-declarations
