### ISSUE TITLE
Don't activate on *

### ISSUE THREAD

**Issue by tristan957** [material-theme/vsc-material-theme#560]
Figured I would forward this issue along: https://github.com/Binaryify/OneDark-Pro/issues/675#issue-1105179777

I looked at this extension's `package.json`, and I saw the `*`. Not sure if it could be changed to `onStartupFinished` or not.

**Comment by equinusocio** [comment]
@LasaleFamine We shouild replace `*` with `onStartupFinished `

**Comment by tristan957** [comment]
:/. Worst bot that ever existed.

**Comment by equinusocio** [comment]
Releasing it with `onStartupFinished`
