### ISSUE TITLE
No focused indicator on noteboooks

### ISSUE THREAD

**Issue by paw-lu** [material-theme/vsc-material-theme#562]
**Describe the bug**

When using note

books in VS Code, a [vertical bar will appear adjacent to the active cell to indicate that it's focused](https://code.visualstudio.com/updates/v1_64#_cell-collapsing-ui).

<img width="697" alt="Screen Shot 2022-02-09 at 8 58 25 AM" src="https://user-images.githubusercontent.com/30049606/153251270-53080212-15d0-4f42-9ef5-1d50399b1e40.png">

But when the Material Theme is applied, a focused indicator is not visible.

<img width="697" alt="Screen Shot 2022-02-09 at 8 59 05 AM" src="https://user-images.githubusercontent.com/30049606/153251368-d361aa98-d7a3-4b2b-8df1-6e20c19cb6a4.png">

**To Reproduce**
1. Open a notebook in VS Code
2. Apply the Material Theme
3. Focus on a cell

**Expected behavior**
I expect the focus indicators to be visible.

---

Thanks for the fantastic theme!

**Comment by paw-lu** [comment]
still an issue! Thanks!

**Comment by paw-lu** [comment]
still an issue! Thanks!

**Comment by equinusocio** [comment]
Released.

**Comment by paw-lu** [comment]
big thanks @equinusocio

appreciated!
