### ISSUE TITLE
Colorful brakets, parenthesis, etc?

### ISSUE THREAD

**Issue by eexit** [material-theme/vsc-material-theme#573]
Hello,

Only this morning I realized something has changed when opening VSCode but I could tell if this is related this theme since it does not seem to have any recent update.

![Screen Shot @ 2022-05-09 at 4 58 48 PM](https://user-images.githubusercontent.com/57098/167438726-15e558b1-aed9-4558-844f-64e026740635.png)

I don't recall having this colorization going on. Happens on any language.
Any clue?

Thanks!

**Comment by eexit** [comment]
Okay, it seems to be out for a while but I wonder what turned this setting on lately on my config:

https://dev.to/vscodetips/native-bracket-pair-colourization-in-vs-code-3f1n

Sorry for the annoyance.

**Comment by equinusocio** [comment]
Maybe they just set `"editor.bracketPairColorization.enabled": true` by default
