### ISSUE TITLE
Post Official Color Schemes w/hex codes

### ISSUE THREAD

**Issue by theamazing0** [material-theme/vsc-material-theme#574]
**Is your feature request related to a problem? Please describe.**
Its kind of annoying to try to port the theme to alternate platforms, especially when I'm trying to setup many different things for my linux desktop.

**Describe the solution you'd like**
An official page/section (maybe on https://material-theme.site/) could show the official hex codes. (like on https://www.nordtheme.com/)

**Describe alternatives you've considered**
It could also be posted on a separate repository on the README.md?

**Additional context**
This feature would make the theme more accessible to users.

**Comment by theamazing0** [comment]
Thanks, please consider making some sort of pointer to that page in the README.md, as this color scheme is truly epic.

**Comment by equinusocio** [comment]
Added to README
