### ISSUE TITLE
The file name color is too dimmed

### ISSUE THREAD

**Issue by mendax1234** [material-theme/vsc-material-theme#579]
**Is your feature request related to a problem? Please describe.**

After using the Material Theme , the file name color is too dimmed

**Describe the solution you'd like**

l would like it to be more clear.

**Describe alternatives you've considered**

None yet

**Additional context**

![image](https://user-images.githubusercontent.com/62934294/175796089-64b31e1c-445a-4296-a6be-8273639b1f56.png)
As you can see from the screenshot, the file name color is too dimmed.

**Comment by equinusocio** [comment]
Hello, this is the intended behaviour and design. You can customize every single part of the theme by following this section of the README
https://github.com/material-theme/vsc-material-theme#override-theme-colors

**Comment by mendax1234** [comment]
Got it! Thank you very much!
