### ISSUE TITLE
improve color palette for better code readability

### ISSUE THREAD

**Issue by rodrigoGA** [material-theme/vsc-material-theme#580]
To highlight the code, the color white is used in excess, this makes it more difficult to read.
For example, a different color could be used for method parameters.

I attach a screenshot of material theme and others themes so you can see the difference

material-theme
![Captura de pantalla de 2022-07-17 16-16-18](https://user-images.githubusercontent.com/2334523/179421684-bdc5ed46-beb9-4d13-a1ca-25a077883747.png)
oneDark Pro
![Captura de pantalla de 2022-07-17 16-17-54](https://user-images.githubusercontent.com/2334523/179421716-9d16981a-d88d-497b-bfbd-c078eb831edb.png)
dracula
![Captura de pantalla de 2022-07-17 16-37-57](https://user-images.githubusercontent.com/2334523/179422112-231bea16-3da1-469a-8d68-31a620e2279a.png)

a good code readability reference i think it could be dracula theme

- https://spec.draculatheme.com/
- https://github.com/dracula/visual-studio-code

**Comment by equinusocio** [comment]
https://github.com/material-theme/vsc-material-theme#override-theme-colors
