### ISSUE TITLE
Switching accent color doesn't work

### ISSUE THREAD

**Issue by ArtyIF** [material-theme/vsc-material-theme#582]
**Describe the bug**
When I try to change the accent color (either via settings or the "Material Theme: Set accent color" command), nothing happens.

**To Reproduce**
1. Open File - Settings
2. Find Material Theme: Accent
3. Change it to anything
4. Nothing happens
5. Open the command palette (Ctrl+Shift+P)
6. Find "Material Theme: Set accent color" command
7. Nothing happens

**Expected behavior**
The accent color will change. In case of the command, some kind of a list should open, or it should open the setting.

**Additional context**
Running on Fedora 36, non-Flatpak (i.e. installed natively without sandboxing). The build directory exists.

**Comment by equinusocio** [comment]
We can't replicate the issue. Can you share console log after running the command?

**Comment by ArtyIF** [comment]
Which one exactly? There are a couple dozen logs, and none of them have anything Material Theme-related.
