### ISSUE TITLE
Will we have Solarized Dark Theme in vsc material theme?

### ISSUE THREAD

**Issue by shenmishajing** [material-theme/vsc-material-theme#585]
**Is your feature request related to a problem? Please describe.**
I really love this theme plugins and I use it in jetbrains IDEs like pycharm etc. for a long time. I prefer the solarized dark theme, but, I find that in the vscode, we do not have the solarized dark theme in material theme. So, will we support this? The builtin one can not highlight self param in python, and is far away from the material solarized dark them in pycharm.

pycharm material solarized dark theme
<img width="1920" alt="截屏2022-11-06 19 01 11" src="https://user-images.githubusercontent.com/32559715/200166941-1ffc07ce-5167-49a2-a725-40a11266200a.png">

vscode builtin solarized dark theme
<img width="1908" alt="截屏2022-11-06 19 01 42" src="https://user-images.githubusercontent.com/32559715/200166962-e745a8c7-21a9-42b6-8c72-8089cade1257.png">

**Describe the solution you'd like**
Add a solaried dark theme in material theme like pycharm's material them.

**Comment by equinusocio** [comment]
Hello, we are not going to support support third-party themes. Material Theme is an original theme with their own hand-crafted color schemes. MT for JetBrains is a independent fork, started from the original theme but now different under many aspect.
