### ISSUE TITLE
Suddenly lost my favourite theme

### ISSUE THREAD

**Issue by ajsaule** [material-theme/vsc-material-theme#586]
I am a big fan of these themes and I was using the `Material Basic` I am pretty sure it was called just that (the current Material Basic theme is totally different to what it used to be). Today I changed my theme to a light theme and seemed to have lost the existing theme that I was using. The syntax highlighting has changed and the colors of buttons, accents, keywords and general panels of the IDE. 

I have a screenshot here of what it used to look like: 

<img width="1782" alt="Screen Shot 2022-06-18 at 1 31 07 pm" src="https://user-images.githubusercontent.com/49604000/200758419-90e48c6a-74f9-4231-9e3b-f5b70d166b3f.png">

How can I get back to this old theme, for some reason it's no longer on my list of themes in settings.

This is what it currently looks like: 

<img width="2027" alt="Screenshot 2022-11-09 at 5 46 33 pm" src="https://user-images.githubusercontent.com/49604000/200758645-581a2883-6497-4a38-addf-9a7ddc903eae.png">

Any help appreciated, thanks.

**Comment by equinusocio** [comment]
Hi, I'm pretty sure you're not using official Material Theme (this extension).

![Screenshot 2022-11-09 at 13 11 20](https://user-images.githubusercontent.com/10454741/200827245-98180216-b053-4caf-a11b-a427732ba9b8.png)

**Comment by ajsaule** [comment]
Ok I think that could be the issue, I think I was using the Community themes or a cloned non-official theme. 

Thanks for clearing that up, I will try and keep searching for my lost theme.
